### ISSUE TITLE
Remove usage of std::unary_function and std::binary_function"

### ISSUE THREAD

**Issue by baristelmen** [thelfer/tfel#104]
On C++17 standards std:unary_function or std::binary_function and several other functions are completely removed. For that reason, starting compilation with VS2017 and oneAPI, the first error is given at the location of;

C:\Apps\tfel\source\4.0\include\NUMODIS\Math\Utilities.hxx on the line 275
\NUMODIS/Math/Utilities.hxx(281): error C2143: syntax error: missing ',' before '<'

The line is as below,

    template <class TYPE>
    struct Abs : public std::unary_function<TYPE, void> {
      //! defines the absolute value function of x
      /*! \param x input value */
      void operator()(TYPE& x) { x = (x >= 0 ? x : -x); }
    };
To bypass or let's say satisfy VS2017 and C++17 requirements, we can define our own unary_function as below.

	template<class ArgumentType, class ResultType>
	struct spp_unary_function
	{
		typedef ArgumentType argument_type;
		typedef ResultType result_type;
	};
And finally, spp_unary_function can be implemented directly to the necessary position,

    template <class TYPE>
    struct Abs : public spp_unary_function<TYPE, void> {
      //! defines the absolute value function of x
      /*! \param x input value */
      void operator()(TYPE& x) { x = (x >= 0 ? x : -x); }
    };

Finally, it compiles and does not complain about the error on version 4.0 with VS2017 using C++17 standards. There are several occasions of std::unary_function on different files and by creating the template as above, the errors (regarding this matter) have vanished.

**Comment by thelfer** [comment]
@baristelmen Just fixed this in the `rliv-4.0` branch. Could you test it ?

**Comment by baristelmen** [comment]
Currently, with the `rliv-4.0`, it's still giving the error with,

```
  struct AbsSum {
    //! \brief a simple alias
    using argument_type = T;
    //! \brief a simple alias
    using result_type = void;
```
By just adding this function directly and changing the `std::unary_function` to `spp_unary_function` (or an another name) fixes the C2143 errors. 

I believe the following code provides a (kind of) `unary_function `template 

```
template<class ArgumentType, class ResultType>
struct spp_unary_function
{
	typedef ArgumentType argument_type;
	typedef ResultType result_type;
};
```

**Comment by thelfer** [comment]
> Currently, with the `rliv-4.0`, it's still giving the error with,

Strange. Since std::unary_function is not used anymore, why should be introduce `spp_unary_function` ? Would it be possible to attach the full VS log ?

**Comment by baristelmen** [comment]
Sorry, it's my bad, I didn't checkout to rliv-4.0 branch. I was working on the master branch. 

Currently, rliv-4.0 branch does not give any errors regarding C2143. 

Just in case, as a reference, here is the `C++` reference page,
https://en.cppreference.com/w/cpp/utility/functional/unary_function

I will try to add a full log once `cmake `finishes its job.

**Comment by thelfer** [comment]
Perfect. I also update the `master` branch. Thanks for your time !

**Comment by thelfer** [comment]
@baristelmen Is it ok now ?
