### ISSUE TITLE
[mfront] Add new viscoplastic law in StandardElastoViscoPlasticity brick

### ISSUE THREAD

**Issue by hureje** [thelfer/tfel#155]
This isssue is about adding a new viscoplastic law in StandardElastoViscoPlasticity brick such as :

dp_dt = F(f,p,...) with f = (sig-X)_eq - R(p)

where the function F is user defined.

**Comment by thelfer** [comment]
@hureje would you test the th/work_issue_155 branch ?

**Comment by thelfer** [comment]
The `UserDefinedViscoplasticity` inelastic flow allows the user to specify the viscoplastic strain rate `vp` as a function of `f` and `p` where:

- `f` is the positive part of \(\phi\paren{\tsigma-\sum_{i}\tenseur{X}_{i}}-\sum_{i}R_{i}\paren{p}\) where \(\phi\) is the stress criterion.
- `p` is the equivalent viscoplastic strain.

This function shall be given in a string option named `vp`. This function must depend on `f`. Dependance to `p` is optional.

The function `vp` may also depend on other variables. Let `A` be such a variable. The `UserDefinedViscoplasticity` flow will look if an option named `A` has been given to the flow:

- If this option exists, it will be interpreted as a material coefficient as usal and this option can be a number, a formula or th name of an external `MFront` file.
- If this option does not exist, a suitable variable will be search in the variables defined in the behaviour (static variables, parameters, material properties, etc...).

If required, the derivatives of `vp` with respect to `f` and `p` can be provided through the options `dvp_df` and `dvp_dp`. The derivatives `dvp_df` and `dvp_dp` can depend on two additional variables, `vp` and `seps`, which denotes the viscoplastic strain rate and a stress threshold.

If those derivatives are not provided, automatic differentiation will be used. The user shall be warned that the automatic differentiation provided by the `tfel::math::Evaluator` class may result in inefficient code.

### Example of usage

```cxx
@Parameter temperature Ta = 600;
@Parameter strain p0 = 1e-8;

@Brick StandardElastoViscoPlasticity{
  stress_potential : "Hooke" {young_modulus : 150e9, poisson_ratio : 0.3},
  inelastic_flow : "UserDefinedViscoplasticity" {
    criterion : "Mises",
    E : 8.2,
    A : "8e-67 * exp(- T / Ta)",
    m : 0.32,
    vp : "A * (f ** E) / ((p + p0) ** m)",
    dvp_df : "E * vp / (max(f, seps))"
    // dvp_dp is evaluated by automatic differentiation (which is not recommended)
  }
};
```

**Comment by Hieppt** [comment]
@hureje @thelfer : In some cases, the derivates dvp_dp and dvp_dp must be defined explicitely in StandardElastoViscoPlasticity brick. Unless, the test (ptest and mtest) cannot converge.

**Comment by thelfer** [comment]
The trouble in your example is that TFEL/Math automatic differentiation computes the derivatives of a power function by considering the exponent as a function, even if constant, and it multiplies the results by 0. However, the derivative may be nan, nan * 0 is still nan...

@Hieppt, @hureje You may want to open a ticket for optimised differentiation that would avoid useless computations and also avoid this issue.
