### ISSUE TITLE
[mfront] Add user defined isotropic hardening in StandardElastoViscoPlasticity brick

### ISSUE THREAD

**Issue by hureje** [thelfer/tfel#158]
Add the possibility for the user to define its own isotropic hardening law in the StandardElastoViscoPlasticity brick :

rp = ....
drp_dp = ...

**Comment by thelfer** [comment]
The `UserDefined` isotropic hardening rule allows the user to specify the radius of the yield surface as a function of the equivalent plastic strain `p`.

This function shall be given by a string option named `R` and must depend on `p`. The function may also depend on other variables. Let `A` be such a variable. The `UserDefined` isotropic hardening rule will look if an option named `A` has been given:

- If this option exists, it will be interpreted as a material coefficient as usal and this option can be a number, a formula or the name of an external `MFront` file.
- If this option does not exist, a suitable variable will be search in the variables defined in the behaviour (static variables, parameters, material properties, etc...).

If required, the derivative of `R` with respect to `f` and `p` can be provided through the option `dR_dp`. The derivative `dR_dp` can depend on the variable `R`.

If this derivative is not provided, automatic differentiation will be used. The user shall be warned that the automatic differentiation provided by the `tfel::math::Evaluator` class may result in inefficient code.

#### Example of usage

```cxx
@Parameter stress R0 = 200e6;
@Parameter stress Hy = 40e6;
@Parameter real b = 100;

@Brick StandardElastoViscoPlasticity{
  stress_potential : "Hooke" {young_modulus : 150e9, poisson_ratio : 0.3},
  inelastic_flow : "Plastic" {
    criterion : "Mises",
    isotropic_hardening : "UserDefined" {
      R : "R0 + Hy * (1 - exp(-b * p))",     // Yield radius
      dR_dp : "b * (R0 + Hy - R)"
    }
  }
};
```

**Comment by Hieppt** [comment]
Thanks @thelfer !

I have tried to creat a behaviour law in which the total strain contains a viscoplastic part (`UserDefinedViscoplasticity`) and a plastic one (`isotropic_hardening : "UserDefined"`). I am not really sure that my syntax is correct for this addition. The error message is as follows :

```
error: ‘seq’ was not declared in this scope; did you mean ‘__pstl::execution::v1::seq’?
```
I attached here the mfront file. Can you take a look ?
[test.zip](https://github.com/thelfer/tfel/files/8478858/test.zip)
 
Regards,
Hiep

**Comment by thelfer** [comment]
@Hieppt Many thanks, this is a bug in the `Plastic` inelastic flow.

**Comment by thelfer** [comment]
@Hieppt It is fixed in `master` now. Thanks for your tests !
