### ISSUE TITLE
[mfront] Orthotropic thermal coefficients in StandardElastoViscoPlasticity Brick

### ISSUE THREAD

**Issue by Hieppt** [thelfer/tfel#160]
Thomas,

Could you add the possibility of defining the orthotropic thermal coefficients in StandardElastoViscoPlasticity Brick : 
```
- ThermalExpansion1
- ThermalExpansion2
- ThermalExpansion3
```
If possible, I would like to define the coefficients as function of temperature in other files and call it in the main mfront file.
Regards,
Hiep

**Comment by thelfer** [comment]
Hi @Hieppt,

I think that this is already the case:

```cxx
@Brick StandardElastoViscoPlasticity{
  stress_potential : "Hooke" {
    young_modulus1 :, 
    young_modulus2 :,
    young_modulus3 :,  
    poisson_ratio12 :,
    poisson_ratio23 :,
    poisson_ratio13 :,
    shear_modulus12 :,
    shear_modulus23 :,
    shear_modulus13 :,
    thermal_expansion1 :,
    thermal_expansion2 :,
    thermal_expansion3 :,
  }
};
```

**Comment by Hieppt** [comment]
@thelfer : Effectively, it works ! Thanks for your help. Could you close the ticket?
