### ISSUE TITLE
[mfront] Addition of several inelastic strains in StandardElastoViscoPlasticity Brick

### ISSUE THREAD

**Issue by Hieppt** [thelfer/tfel#161]
Hi,

I discover that if several `inelastic_flow` blocks are present in `StandardElastoViscoPlasticity `Brick, I cannot declare intermediate variable (like `a` in the following example). While only one `inelastic_flow` block is present, everything seems ok.

```
  inelastic_flow : "UserDefinedViscoplasticity" {
    criterion : "Hill" {F : 0.29, G : 0.71, H : 0.33, L : 1.5, M : 1.5, N : 1.5},
    vp : "1. * f"
  },
  inelastic_flow : "UserDefinedViscoplasticity" {
    criterion : "Mises",
    a : "2.",
    vp : "a * f"
  }
```

Error message :
`BehaviourDescription::getMaterialPropertyInputCategory: unsupported variable: variable 'a' is neither an external state variable, a material property nor a parameter nor an auxiliary state variable evaluated by an external model, nor a static variable
`

Regards,
Hiep

**Comment by thelfer** [comment]
@Hieppt Fixed in `master`. Thanks for reporting !
