### ISSUE TITLE
[mfront] Minors issues of syntax in StandardElastoViscoPlasticity Brick

### ISSUE THREAD

**Issue by Hieppt** [thelfer/tfel#162]
Hi,

I would like to report some minors issues that I have discovered by working with StandardElastoViscoPlasticity Brick.
- **Scientific format numbers :** smalle `e` (ex: `1e3` )is accepted, but not `E` (ex: `1E3`).
Error message : `Evaluator::analyse: analysis of formula '1E3 * f' failed (TGroup::analyse: tgroup has not been reduced.)`

- **Numbers types** : the following syntax is accepted
```
  inelastic_flow : "UserDefinedViscoplasticity" {
    criterion : "Hill" {F : 0.29, G : 0.71, H : 0.33, L : 1.5, M : 1.5, N : 1.5},
    vp : "1. * f"
  }
```
but not this one :
```
  inelastic_flow : "UserDefinedViscoplasticity" {
    criterion : "Hill" {F : 0.29, G : 0.71, H : 0.33, L : 1.5, M : 1.5, N : 1.5},
    vp : "f "
  }
```
Error message : `inconsistent types ‘int’ and ‘double’ deduced for lambda return type`

**Comment by thelfer** [comment]
The issue concerning the Scientific format numbers is fixed in `rliv-3.0` and all the other `rliv` branches and `master`.
The issue concerning the `StandardElastoViscoPlasticity` brick is fixed in `master`.
