### ISSUE TITLE
Documentation: disable-reference-doc & disable-website not used

### ISSUE THREAD

**Issue by leopeuziat** [thelfer/tfel#166]
In installation guide (http://tfel.sourceforge.net/install.html) section 3.2.1 "Controlling the generation of the documentation", the cmake variables "disable-reference-doc" and "disable-website" are proposed.
In rliv-3.4 commit 41c82ee, when I use these cmake variables, during the configuration step, I get the following warning:
CMake Warning:
  Manually-specified variables were not used by the project:

    disable-reference-doc
    disable-website

**Comment by thelfer** [comment]
@leopeuziat Thanks for the feed-back. The correct syntax is: `-Denable-reference-doc=OFF` and `-Denable-website=OFF`.
