### ISSUE TITLE
[mtest] Usage of a 3D behaviour in `ptest`

### ISSUE THREAD

**Issue by ceciliagicquel** [thelfer/tfel#18]
I would like to use the ptest tool with a 3D model, but in order to do that the results must be projected to 1D.

**Comment by thelfer** [comment]
Hi @ceciliagicquel,

Thanks for this interesting proposal. Modelling of pipe tests is done using the axisymmetrical generalized plane strain modelling hypothesis.

Two remarks:

1. A theoritical one: using 3D behaviours would require to neglect the shear components of the strain and stresses. This only makes senses for a limited (but pratically important) subset of the cases.
2. A pratical one: the size of tensors being different between 1D and 3D hypotheses, the only thing that we can do with minimal effort given the current `MTest` API is to convert 3D tensors into array of state variables. This will affect the usage of some keywords such as `@InternalStateVariable`, etc...

If ok for you, I will make a first proposal and request your review.

Best,

Thomas

**Comment by ceciliagicquel** [comment]
Thank you @thelfer for your answer,


I think it is ok, I am not using the `@InternalStateVariable` keyword but I do use (and need) the `@Parameter` one, I do not know if that is a problem. 

Cecilia

**Comment by ceciliagicquel** [comment]
Hi @thelfer 
Just a question : When you say  "neglect the shear components of the strain and stresses" does that refer only to macroscopic quantities or microscopic too ?  

Cecilia

**Comment by thelfer** [comment]
Hi @ceciliagicquel.
This statement only applies to the macroscopic strain and stresses.
Thomas

**Comment by ceciliagicquel** [comment]
Okay, thank you !

Cecilia

**Comment by thelfer** [comment]
@ceciliagicquel You can test this new feature in the `master` branch. Please have a look at the release notes of the future Version 4.1 : <https://thelfer.github.io/tfel/web/release-notes-4.1.html#sec:tfel_4.1:mtest:small_strain_tridimensional_behaviour_wrapper>
