### ISSUE TITLE
[mfront] The rkCastem algorithm assumes that a variable young is defined.

### ISSUE THREAD

**Issue by Tseyram** [thelfer/tfel#183]
![Capture2](https://user-images.githubusercontent.com/91077350/167304477-5bfab638-b58a-459a-b745-a6c5bcf7fc87.png)

Hi. I'm getting an error when i try to use the rkCastem algorithm.
I need help please.
Thanks
Eyram

**Comment by thelfer** [comment]
Hi @Tseyram,

Thanks for reporting this issue. Indeed the `rkCast3M` assumes that a variable named `young` exists to normalize the 
integration error.

As a workaround, you can define a parameter with the correct order of magnitude, as follows:

~~~~{.cxx}
@Parameter stress young = 100e9;
~~~~

We are working for a more satisfying solution.

**Comment by Tseyram** [comment]
Thanks @thelfer 
I applied your advice and it's working.

**Comment by thelfer** [comment]
## Improvements in Version 4.1

The `rkCastem` algorithm compares the values of the stress computed by a predictor step and corrector step. The error between those values must be normalised. In previous versions, the existence of a variable named `young` was assumed.

The `@StressErrorNormalizationFactor` allows to specify this normalization factor more explicitely and consistenly.

For backward compatibility with previous versions, the `young` variable will be used, if an appropriate variable is defined and if the `@StressErrorNormalizationFactor` keyword was not used.

Note that if the `@StressErrorNormalizationFactor` keyword is not used and that the `young` variable is not defined, `MFront` will look is the stiffnes matrix is defined and take its first component.
