### ISSUE TITLE
[mfront] Get @Material, @Law, @Author, @Date, @Description from compiled file through Python binding

### ISSUE THREAD

**Issue by leopeuziat** [thelfer/tfel#186]
I would like to retrieve metadata (@Material, @Law, @Author, @Date, @Description) from a compile file .so through ExternalLibraryManager (tfel.system) Python binding.

**Comment by thelfer** [comment]
## Improvements to the `ExternalLibraraManager` class

### The `getLaw` method

The `getLaw` method returns the law name associated with a material property as defined by the `@Law` keyword in `MFront`.

### The `getAuthor` method

The `getAuthor` method returns the author name associated with an entry point as defined by the `@Author` keyword in `MFront`. If this author name is not defined, an empty string is returned.

### The `getDate` method

The `getDate` method returns the date associated with an entry point as defined by the `@Date` keyword in `MFront`. If this date is not defined, an empty string is returned.

### The `getDescription` method

The `getDescription` method returns the description associated with an entry point as defined by the `@Description` keyword in `MFront`. If this description is not defined, an empty string is returned.

### The `getMaterialPropertyOutput` method

The `getMaterialPropertyOutput` method returns the external name associated with the output of a material property.

## New class `ExternalMaterialKnowledgeDescription`

The `ExternalMaterialKnowledgeDescription` gathers information exported by `MFront` about an entry point (material property or behaviour). This class has been introduced as a base class for the `ExternalMaterialPropertyDescription` and `ExternalBehaviourDescription` classes.

This class exposes the following data members:

- `library`: the name of the library
- `entry_point`: the name of the entry point
- `tfel_version`: the version of TFEL used to generate the entry point
- `build_id`: the build identifier (if any)
- `source`: the MFront source file
- `mfront_interface`: the name of the interface used to generate the entry point.
- `material`: the name of the material, as introduced by the `@Material` keyword in `MFront`.
- `author`: the author of the implementation, as introduced by the `@Author` keyword in `MFront`.
- `date`: the date of the implementation, as introduced by the `@Date` keyword in `MFront`.
- `description`: the description of the entry point, as introduced by the `@Description` keyword in `MFront`.

## Improvements to the `ExternalMaterialPropertyDescription` class

The `ExternalMaterialPropertyDescription` class now inherits from the `ExternalMaterialKnowledgeDescription` class.
