### ISSUE TITLE
[mfront] Get @Output from compiled file through Python binding

### ISSUE THREAD

**Issue by leopeuziat** [thelfer/tfel#187]
I would like to retrieve the name of the output variable @Output from a compile file .so through ExternalLibraryManager (tfel.system) Python binding.
For input variable I use:
from tfel.system import ExternalLibraryManager
elem = ExternalLibraryManager.getExternalLibraryManager()
print(elem.getMaterialPropertyVariables('vanadiumalloy.so','VanadiumAlloy_YoungModulus_SRMA'))

**Comment by thelfer** [comment]
## Improvments to the `ExternalLibraryManager` 

The `ExternalLibraryManager` class now exposes a member called `getMaterialPropertyOutput` which returns the external name of the output of a material property.

## Improvments to the `ExternalMaterialPropertyDescription` 

The `ExternalMaterialPropertyDescription` class now exposes a data member called `output` which reflects the external name of the output of a material property.
