### ISSUE TITLE
[mfront] Addition of orthotropic kinematic hardening in StandardElastoViscoPlasticity Brick

### ISSUE THREAD

**Issue by Hieppt** [thelfer/tfel#226]
Hi,

I would like to code a behavior law in MFront with orthotropic kinematic hardening. The formulation of the non-dimensionnal internal stress $a=\frac{X}{C}$ ( $X$ is the internal stress and $C$ is a constant) : 

$$ \dot{a} = E_c \cdot \dot{\varepsilon^{vp}} - D \dot{p} R_d \cdot a  - f(a^{eq}, T, \phi_t) \frac{R_s \cdot a}{a^{eq}}$$

where $\varepsilon^{vp}$ is the viscoplastic strain, $p$ is the cumulative plastic strain, $E_c, R_d, R_s$ are orthotropic tensors, $D$ is a constant. The temperature $T$ and the fluence $\phi_t$ are the internal variables.

I will be so glad if this formulation can be coded with StandardElastoViscoPlasticity Brick.

Regard,
Hiep

**Comment by thelfer** [comment]
Hi @Hieppt,

Sorry for the late reply.

I don't understand what is the role of $\phi_t$. Did you mean external state variable (something like neutron fluence ?) ? If $\phi_t$ is an internal state variable, then you shall provide its evolution law.

Is $E_{c}$ a fourth order tensor ? If so, can you give its expression the material frame for an orthotropic material ? 

Also, I don't understand the link between $D$ and $R_{d}$. How do you distinguish them ?
