### ISSUE TITLE
[mfront] Document the variable affecting the compilation of shared libraries

### ISSUE THREAD

**Issue by thelfer** [thelfer/tfel#235]

**Comment by kuateric** [comment]
```
XX=g++-11 mfront --obuild --interface=python youngmodulus.mfront
Treating target : all
make: *** Keine Regel vorhanden, um das Ziel „/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_7/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/include-fixed/limits.h“, 
  benötigt von „YoungModulus-python.o“, zu erstellen.  Schluss.
callMake: can't build target 'all'
libraries building went wrong
Command was: make -C src -f Makefile.mfront all -s 
```

**Comment by thelfer** [comment]
You see to have forgottent the `C` in `CXX`. You must also remove the `include` and `src` directory when the compiler is changed. Otherwise, you may have this kind of strange behaviours (remember `mfront` keeps tracks of the previous compilation)

**Comment by thelfer** [comment]
`mfront` handles the compilation of shared libraries. More precisely, the compilation phase is delegated to external tools called generators in the `mfront` wording. `mfront` currently supports two generators: `make` and `cmake`.

In both cases, the compilation process can be affected by defining any of the following *optional* environment variables:

- `TFELHOME`: this variable must contain the path where `mfront` is installed. This variable is used by `tfel-config` to return the path  to the header files and libraries delivered by the TFEL project. This variable thus affects the output of the following commands (see `tfel-config --help` for details):
  - `tfel-config --includes` and `tfel-config --include-path`
  - `tfel-config --libs` and `tfel-config --library-path`
- `CXX`: this variable defines the `C++` compiler to be used. Note that this choice must be consistent with the compiler used to compile `mfront` if the compiler flags defined by default by `mfront` are used (see below).
- `CXXFLAGS`: this variable defines the compiler flags to be used. If this variable is not defined, `mfront` will use the following outputs of `tfel-config` (see `tfel-config --help` for details): `tfel-config --warnings --compiler-flags --cppflags --cxx-standard`.
  Those compiler flags are completed by the following outputs of `tfel-config` depending on the level of optimisation requested by the user using the `--obuild` command line option of `mfront`:

  - with `--obuild=level0`: `tfel-config --oflags0`
  - with `--obuild=level1` (or simply `--obuild`): `tfel-config --oflags`
  - with `--obuild=level2`: `tfel-config --oflags --oflags2`

  If the `-g` command line option is passed to `mfront`, those flags are completed by the following output of `tfel-config`: `tfel-config --debug-flags`

**Comment by kuateric** [comment]
after removing the old cgg that was link to mfront, I recompiled again and everything works properly. No need to add the CXX in the bash file:
```
eric@X1-Linux-Simo:~/mfront_schulung$ mfront --obuild --interface=python youngmodulus.mfront
Treating target : all
The following library has been built :
- materiallaw.so :  YoungModulus
eric@X1-Linux-Simo:~/mfront_schulung$ which mfront
/opt/programme/mfront/mfront-4.1.0.1/build/bin/mfront
eric@X1-Linux-Simo:~/mfront_schulung$ 
```

**Comment by thelfer** [comment]
See this page for the lastest version of the documentation of the compilation process used by `MFront`: <https://thelfer.github.io/tfel/web/compiling-mfront-shared-libraries.html>
