### ISSUE TITLE
[mfront] Add ability to define initialisation functions

### ISSUE THREAD

**Issue by thelfer** [thelfer/tfel#25]

**Comment by thelfer** [comment]
The `@InitializeFunction` keyword introduces a code block that can be
used to initialize internal state variables at the very beginning of the
computation. Initalize functions may have user so-called
*initialize funtion variables*.

In this version, only the `generic` interface generates functions
associated with initialize functions (See Section
@sec::tfel_4.1:system:elm:initialize_functions to see how to retrieve
the initialize functions generated by the `generic` interfaces).

Because initialize functions are called before any behaviour
integration, special care to the meaning of the variables must be taken:

- The gradients and external state variable will have their values at
  the beginning of the time step and their increments will be null.
- The thermodynamic forces will have their values at the beginning of
  the time step.
- The state variables and auxiliary state variables will have undefined
  values. The associated increments, if defined, will be null.

Concerning material properties, they have their values at the beginning
of the time step.

> **About initialisation of local variables**
>
> The code block defined by the `@InitLocalVariables` code block
> shall be called before the execution of an initialize function.

## Example of usage

The following code defines an initializer function which initializes the
elastic strain from the value of stress:

~~~~{.cxx}
@InitializeFunction ElasticStrainFromInitialStress{
  const auto K = 2 / (3 * (1 - 2 * nu));
  const auto pr = trace(sig) / 3;
  const auto s = deviator(sig);
  eel = eval((pr / K) * Stensor::Id() + s / mu);
}
~~~~

**Comment by cenguo** [comment]
Hi Thomas,
Thanks for your effort in helping implementing the initialization function. If I understand you correctly, now we can use InitializeFunction to initialize the stress as well as all the other internal variables in one block, right? In my opinion, it is much neater than that proposed in https://github.com/thelfer/tfel/issues/24 and https://github.com/thelfer/MFrontGenericInterfaceSupport/issues/50 using different blocks to initialize different variables. Please correct me if I'm wrong.
Best,
Ning

**Comment by thelfer** [comment]
@cenguo You're right. The user may define comprehensive intialize functions which would match its need. But, the idea is also to be able to define fine grain initialize functions that could be generated automatically by the StandardElasticity brick for example.  For example, a default initialize function for the elastic strain from the stress would be nice.
