### ISSUE TITLE
[tfel-math] Add support to clamp TFEL/Math arrays

### ISSUE THREAD

**Issue by pbouda95** [thelfer/tfel#256]
This might be seen as the equivalent of the standard ``std::clamp`` fuction available since C++17.

Cheers,

**Comment by thelfer** [comment]
@pbouda95 Do you mean `std::clamp` ?

**Comment by pbouda95** [comment]
My bad i was confusing python and c++ ... You are right.

**Comment by thelfer** [comment]
@pbouda95 Could you precise what you want exactly and provide an example. I am not sure of what you want to do :)

**Comment by pbouda95** [comment]
@thelfer, sorry for not to be accurate enough.

``std::clamp`` may allow to clip 0-rank variables easily however in a case of a vector-like one (e.g. a vector of hardening variables) I would like to clip components alltogether without looping ...

**Comment by thelfer** [comment]
You mean something like:

```cxx
template<typename ArrayType, >
constexpr void clamp_array(ArrayType& array, const tfel::math::numeric_type<ArrayType>& lo, const tfel::math::numeric_type<ArrayType>& hi){
  std::for_each(array.begin(), array.end(), [lo, hi]( auto& v ){
    if(v < lo){
      v = l0;
    } else if(v>hi){
      v = hi
    }
  });
}
```

**Comment by pbouda95** [comment]
This is absolutely what I was expecting ... A piece of code is better than everything :-)

**Comment by thelfer** [comment]
Do you want it to be included in `TFEL/Math` ?

**Comment by pbouda95** [comment]
That could be nice ...

**Comment by thelfer** [comment]
The `clamp` method is available in all mutable arrays in `TFEL/Math`, including all tensorial objects (`stensor`, `tmatrix`, `st2tost2`, etc..).

### Example of usage

~~~~{.cxx}
constexpr auto a = [] {
  auto values = tfel::math::fsarray<3u, int>{-14, 12, -3};
  values.clamp(-4, 4);
  return values;
}();
static_assert(a[0] == -4);
static_assert(a[1] == 4);
static_assert(a[2] == -3);
~~~~
