### ISSUE TITLE
Installation for TFEL.

### ISSUE THREAD

**Issue by blackdk125** [thelfer/tfel#259]
Dear @thelfer,

Thanks for your reply on Sourceforge! I send a mail on SourceForge, but it is awaiting moderation for a long time.

Following the tutorial, I meet some issues in the process of installation.

1. Compressed package. The file '[tfel-4.0.0](https://sourceforge.net/projects/tfel/files/tfel-4.0.0.tar.gz/download)' that was downloaded from SourceForge can not be decompressed in Ubuntu 22.04, because there is an empty file named as 'readme'.

2. When a command
[cmake $srcdir -DCMAKE_BUILD_TYPE=Release -Dlocal-castem-header=ON -Denable-fortran=ON -Denable-aster=ON -DCMAKE_INSTALL_PREFIX=$prefix] 
executed, some warnings presented:

`CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.`
`CMake Warning (dev) at mfront/tests/models/interfaces/src/CMakeLists.txt:2 (add_library):
  Policy CMP0115 is not set: Source file extensions must be explicit.  Run
  "cmake --help-policy CMP0115" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  File:

    /home/rzye/tfel/version/tfel410dev/source/tfel/mfront/tests/models/interfaces/src/LicosModelInterface.cxx
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at mfront/tests/models/interfaces/src/CMakeLists.txt:9 (add_library):
  Policy CMP0115 is not set: Source file extensions must be explicit.  Run
  "cmake --help-policy CMP0115" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  File:

    /home/rzye/tfel/version/tfel410dev/source/tfel/mfront/tests/models/interfaces/src/MFrontPleiadesModelInterfaceBase.cxx
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at mfront/tests/models/interfaces/src/CMakeLists.txt:9 (add_library):
  Policy CMP0115 is not set: Source file extensions must be explicit.  Run
  "cmake --help-policy CMP0115" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  File:

    /home/rzye/tfel/version/tfel410dev/source/tfel/mfront/tests/models/interfaces/src/MFrontGerminalModelInterface.cxx
This warning is for project developers.  Use -Wno-dev to suppress it.`

Although it has been generated, I do not know whether these warnings affect build.

3. When executed 'make check', it reported the errors:

```
FAIL: ../../../tfel-check/src/tfel-check
============================================================================
Testsuite summary for tfel 4.1.0-dev
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See tfel-check/tests/pass/test-suite.log
Please report to tfel-contact@cea.fr
============================================================================

```

**Comment by blackdk125** [comment]
Dear @thelfer,

I would like to get some advice from you, my project is to build a new constitutive law for some novel metals, not only for slip, it will also focus on twinning and precipitation, etc. Thus, we need an appropriate version of TFEL to generate UMAT, and our aim is to do visualization by Abaqus.
 
If it is possible, we want a version that can define sliding and twinning systems explicit, and my e-mail is 
[dengruijie@foxmail.com], I am looking forward to your reply!

**Comment by thelfer** [comment]
Hi @blackdk125 

Concerning Feed-Back 1, sourceforge let you removed the `.gz` extension to the file, it must be renamed as `tfel-4.0.0.tar.gz`. I don't have a clue with it is like this...

Concerning Feed-Back 3, I don't have any issue excuting the tests with `master` and `tfel-4.0.0` with the `autotools` under `Ubuntu-22.04`.

**Comment by blackdk125** [comment]
Thank you, @thelfer

I tried to install tfei-4.0.0 again, but the error still presented. 

More details have been collected in a document 'docx', and I have sent it to your Email (thomas.helfer@cea.fr).

**Comment by blackdk125** [comment]
Hi, @thelfer 

The error presented is:
`FAIL: ../../../tfel-check/src/tfel-check
============================================================================
Testsuite summary for tfel 4.0.0
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See tfel-check/tests/pass/test-suite.log
Please report to tfel-contact@cea.fr
============================================================================
`

**Comment by thelfer** [comment]
Thanks for your detailled file.
It contains some inconstencies. You seem to mix `cmake` and `configure`. Let us separate concerns. Would you follow the following instructions.

First create a new directory. Let us say  `/home/rzye/tfel/version/tfel400/src`. Uncompress the tar ball there. It is important to start from the a fresh source.

## `cmake` install

```bash
$ mkdir /home/rzye/tfel/version/tfel400/build-cmake
$ cd /home/rzye/tfel/version/tfel400/build-cmake
$ cmake /home/rzye/tfel/version/tfel400/src/tfel-4.0.0 -DCMAKE_BUILD_TYPE=Release -Dlocal-castem-header=ON -Denable-fortran=ON -Denable-aster=ON  -Denable-abaqus=ON -DCMAKE_INSTALL_PREFIX=/home/rzye/tfel/version/tfel400/install-cmake &> cmake-log-1.txt
$ make &>  cmake-log-2.txt
$ make check &>  cmake-log-3.txt
& make install &>  cmake-log-4.txt
```
Please attach the file `cmake-log*.txt` to this thread.

## `autotools` install

```bash
$ mkdir /home/rzye/tfel/version/tfel400/build-autotools
$ cd /home/rzye/tfel/version/tfel400/build-autotools
$ /home/rzye/tfel/version/tfel400/src/tfel-4.0.0/configure --enable-fortran --enable-aster --enable-abaqus --enable-tests --enable-local-castem-header --prefix=/home/rzye/tfel/version/tfel400/install-autotools &> autotools-log-1.txt
$ make &> autotools-log-2.txt
$ make check &> autotools-log-3.txt
$ make install &> autotools-log-4.txt
```

P.S. Note that I added support for the `abaqus` interface

**Comment by blackdk125** [comment]
Thanks for your reply.


I will install again by your toutorial.


&nbsp;AP Mr. Ling Chao has set a correct&nbsp;path for me, and I can compile the routine in Gauss point now.


But it still present some errors in 'make check'.
======
entering directory '/home/rzye/tfel/version/tfel400/source/tfel-check/tests/pass'
* beginning of test './test5.check'
** Exec-1 ./test5&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^[[32m [SUCCESS]^[[m^O
** Compare-1 'test5.ref' and 'test5.res', column 'B'&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ^[[31m [ FAILED]^[[m^O
* end of test './test5.check'&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^[[31m [ FAILED]^[[m^O
======

It show a different calculation in test5.


Which is in 'test5.rec'
======
tps B C
1. 2. 2.
2. 3. 1.
3.2 6. 1.
4 7. 1.

======
&nbsp;
and calculation in 'test5.ref'
=======
tps B C
1. 2. 2.
2. 3. 1.
3. 4.5 1.
3.5 6. 1
4. 7. 1.

=======


I have no idea about whether it affects the validity of our subroutine.


I have posted a similar mail on github, you can reply to any feedback.


Best Regards,&nbsp;


Deng ruijie






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thelfer/tfel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月16日(星期六) 下午4:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [thelfer/tfel] Installation for TFEL. (Issue #259)





 
Thanks for your detailled file.
 It contains some inconstencies. You seem to mix cmake and configure. Let us separate concerns. Would you follow the following instructions.
 
First create a new directory. Let us say  /home/rzye/tfel/version/tfel400/src. Uncompress the tar ball there. It is important to start from the a fresh source.
 
cmake install
 $ mkdir /home/rzye/tfel/version/tfel400/build-cmake $ cd /home/rzye/tfel/version/tfel400/build-cmake $ cmake /home/rzye/tfel/version/tfel400/src/tfel-4.0.0 -DCMAKE_BUILD_TYPE=Release -Dlocal-castem-header=ON -Denable-fortran=ON -Denable-aster=ON  -Denable-abaqus=ON -DCMAKE_INSTALL_PREFIX=/home/rzye/tfel/version/tfel400/install-cmake &amp;&gt; cmake-log-1.txt $ make &amp;&gt;  cmake-log-2.txt $ make check &amp;&gt;  cmake-log-3.txt &amp; make install &amp;&gt;  cmake-log-4.txt
 
Please attach the file cmake-log*.txt to this thread.
 
autotools install
 $ mkdir /home/rzye/tfel/version/tfel400/build-autotools $ cd /home/rzye/tfel/version/tfel400/build-autotools $ /home/rzye/tfel/version/tfel400/src/tfel-4.0.0/configure --enable-fortran --enable-aster --enable-abaqus --enable-tests --enable-local-castem-header --prefix=/home/rzye/tfel/version/tfel400/install-autotools &amp;&gt; autotools-log-1.txt $ make &amp;&gt; autotools-log-2.txt $ make check &amp;&gt; autotools-log-3.txt $ make install &amp;&gt; autotools-log-4.txt
 
P.S. Note that I added support for the abaqus interface

**Comment by blackdk125** [comment]
Hi, @thelfer 

The errors presented in `make check` as

```
FAIL: ../../../tfel-check/src/tfel-check
============================================================================
Testsuite summary for tfel 4.0.0
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See tfel-check/tests/pass/test-suite.log
Please report to tfel-contact@cea.fr
============================================================================

````

But it still presents some errors in 'make check'.

```
======
entering directory '/home/rzye/tfel/version/tfel400/source/tfel-check/tests/pass'
* beginning of test './test5.check'
** Exec-1 ./test5                                                     ^[[32m [SUCCESS]^[[m^O
** Compare-1 'test5.ref' and 'test5.res', column 'B'                  ^[[31m [ FAILED]^[[m^O
* end of test './test5.check'                                         ^[[31m [ FAILED]^[[m^O
======

```
It show a different calculation in test5.

Which is in 'test5.rec'
```
======
tps B C
1. 2. 2.
2. 3. 1.
3.2 6. 1.
4 7. 1.
======

``` 
and calculation in 'test5.ref'

```
=======
tps B C
1. 2. 2.
2. 3. 1.
3. 4.5 1.
3.5 6. 1
4. 7. 1.
=======

```

**Comment by thelfer** [comment]
Looks like there is a bug in the `Makefile.am` file in `tfel-check/tests/pass`, so basically `test4` and `test5` must be the same, which is the case on my machine. I suspect the autotools to do some strange things when copying the file because the test4.ref is in thus in the build and src directory. Netherless, even if I can't reproduce the issue, you found something. Bravo !

In the end, you can discard this result. Your mfront installation shall work properly in spite of this issue.

**Comment by blackdk125** [comment]
Dera Helfer.




Thank you very much for your patient and detailed reply! Mfront has been installed in my machine, and I will try your new tutorial again in other computer.








In the previous installation, I did not set the corresponding PATH for Mfront, so the routine can not be run in my machine. With the help by Mr.Ling Chao, I can execute Mfront now.




I'm sure we'll still need your help in the future.


Thanks for your help and description!


Best regards!






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thelfer/tfel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月16日(星期六) 晚上7:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [thelfer/tfel] Installation for TFEL. (Issue #259)





 
Looks like there is a bug in the Makefile.am file in tfel-check/tests/pass, so basically test4 and test5 must be the same, which is the case on my machine. I suspect the autotools to do some strange things when copying the file because the test4.ref is in thus in the build and src directory. Netherless, even if I can't reproduce the issue, you found something. Bravo !
 
In the end, you can discard this result. Your mfront installation shall work properly in spite of this issue.

**Comment by blackdk125** [comment]
Hi, @thelfer.

I've compiled some questions into a file and sent it to your email "tfel-contact@cea.fr".

Waiting for your reply.
