### ISSUE TITLE
[mfront] Addition of isotropic hardening rule defined by points in the StandardElastoViscoPlasticity Brick

### ISSUE THREAD

**Issue by jb251061** [thelfer/tfel#261]
Hi,

I would like to be able to define an isotropic hardening rule by providing a list of points $(p_i, \sigma_i)$ where $p_i$ is the cumulative plastic strain and $\sigma_i$ is the correponding stress.
It would be nice to have this alongside the Linear, Swift, Power and Voce rules already available in the StandardElastoViscoPlasticity Brick.

Kind regards,

Joffrey

**Comment by thelfer** [comment]
@jb251061 This would indeed by a nice addition. You must however specify how you want the data to be interpolated (linear interpolation, spline) and extrapolated.

**Comment by jb251061** [comment]
Personally I would copy Cast3M and use a linear interpolation and extrapolate using the last value (i.e. perfect plasticity beyond the last point).
I don't know if that's the best way to go about it but at least that's what I'm used to!

**Comment by thelfer** [comment]
Would the following syntax be ok (do not hesitate to improve it):

```c++
  inelastic_flow : "Plastic" {
    criterion : "Mises",
    isotropic_hardening : "DataInteroplation" {
      interpolation : "linear",
      extrapolation : false,
      values : {0 : 0, 1.2e-2 : 150e6}
    }
```

That would allow for other kind of interpolation (spline) and extrapolation.

**Comment by jb251061** [comment]
That looks great :)
The only thing I would change is `extrapolation : false`. I would use `extrapolation : constant` instead, because using the last value to extend the curve is still a kind of extrapolation. For me `extrapolation : false` sounds like it's not possible to go beyond the defined range (the program should throw an error or something).
Plus it means one could also potentially use different kinds of extrapolation.
Apart from that I like this syntax very much!

**Comment by thelfer** [comment]
@jb251061 Thanks for the feed-back. Indeed, your proposal does make sense. I'll try to implement that next week.

**Comment by thelfer** [comment]
@jb251061 Just pushed a first version. Would you test it ?
