### ISSUE TITLE
Installation issue of the `master` branch (version 4.1) with `gcc-8.1.0`

### ISSUE THREAD

**Issue by LionelGelebart** [thelfer/tfel#262]
Installation issue with gcc810 : "make check" fails

**Comment by thelfer** [comment]
Hi @LionelGelebart,

Trouble seems to be related to compiler bugs. `gcc-8.3` works fine.

More precisely, this compiler is not able to build behaviours based on quantities (numbers with units) which were introduced in Version 4.0. Quantities requires a conformant `C++-17` compiler.

What about adding an option named `enable-mfront-quantity-tests` to `cmake`? (This option would be `ON` by default and these test will be disabled if the flag `-Denable-mfront-quantity-tests=OFF` is passed to `cmake`)

**Comment by thelfer** [comment]
Hi @LionelGelebart. I implemented the `enable-mfront-quantity-tests` option. Would you check it ?
