### ISSUE TITLE
Python binding of ExternalMaterialPropertyDescription class: error with attribut "description" 

### ISSUE THREAD

**Issue by leopeuziat** [thelfer/tfel#267]
When there is an accent (éè) in the @Description of a MFront file, an error is raised when reading ExternalMaterialPropertyDescription.description with the Python binding

For instance with the file VanadiumAlloy_PoissonRatio_SRMA.mfront from the MFrontGallery database:

```
prop = ExternalMaterialPropertyDescription(src/libCastemVanadiumAlloy.so,VanadiumAlloy_PoissonRatio_SRMA)
prop.description
```

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 4: invalid continuation byte`

commit 831752958ff81002d114a5d85f79cf3c24114885 du 02/08/2022

**Comment by thelfer** [comment]
Hi @leopeuziat,

The trouble is on the `python` side.

`MFront` does not care wheter your file is encoded in latin9, UTF-8 or anything else. It basically reads bytes (8-bits characters) and stores it.

 You can handle the issue on the `python` side, but this is cumbersome. You'd better convert all your `MFront` file to `UTF-8` using something like `iconv`.

Note that [`tfel-editor`](https://github.com/thelfer/tfel-editor) automatically converts and saves all files to `UTF-8`.

**Comment by leopeuziat** [comment]
The trouble is somewhere in the pythonbinding. In my python script the error occurs when I call the "description" attribut. The call returns an error in my script, not a value. I can do nothing to manage this.

**Comment by pbouda95** [comment]
Hello folks,

I am not sure if this could help but the issue of string encoding with Python is now better handled since a few years ago.
If the reader is properly defined, the basic python string is now an unicode string and has to be convert using the `decode` method according to a standard. Then you can choose one which handle french characters. You can fine more information here:
https://docs.python.org/3/library/codecs.html#standard-encodings

Cheers,

**Comment by thelfer** [comment]
@pbouda95 Thanks for the tip !

**Comment by leopeuziat** [comment]
Working with UTF-8 mfront file is solving the problem.

**Comment by thelfer** [comment]
> Working with UTF-8 mfront file is solving the problem.

Indeed, I checked a little bit and did not find any satisfying solution. I added this to my best practices guide
