### ISSUE TITLE
[mfront] Add a behaviour interface for  `PLAXIS`

### ISSUE THREAD

**Issue by thelfer** [thelfer/tfel#272]
The aim of this issue is to create an interface for [`PLAXIS`](https://www.bentley.com/fr/products/brands/plaxis).

**Comment by MManicaM** [comment]
Excellent!
More than happy to collaborate on this issue!

**Comment by thelfer** [comment]
1. I have to compile `TFEL/MFront` with the Intel compilers on Windows
2. I have to check how to make `Fortran/C++` bindings to ease things for MFront
3. We would use an external text file to associate the Model Id from Plaxis to an MFront behaviour. This file could look like this:
     ~~~~~
     1 CamClay2024 MFrontPlaxis
     2 MohrCoulomb MFrontPlaxis2
     ~~~~~

**Comment by thelfer** [comment]
A `PLAXIS` interface can be implemented on top of `MGIS` as demonstrated here: https://github.com/thelfer/plaxis-udm
