### ISSUE TITLE
Inconsistency in the GursonTvergaardNeedleman model in the StandardElastoViscoPlasticity brick

### ISSUE THREAD

**Issue by hureje** [thelfer/tfel#277]
In the code (and the documentation : §2.1 in http://tfel.sourceforge.net/StandardElastoViscoPlasticityBrick-PorousPlasticity.html#Stress_criteria) the ultimate value of the effective porosity (corresponding to the value of porosity for which the stress is equal to zero according to the yield criterion) is defined as f_ult = 1 / q_1, which is true only for q_3 = q_1^2. In the current implementation, taking q_3 different from q_1^2 may lead to divergence. In the general case, the ultimate porosity is the root of : 2 * q_1 * f -1 -q_3 * f * f.

**Comment by thelfer** [comment]
Thanks for reporting the issue. Would you try to propose a fix ?

**Comment by hureje** [comment]
[GursonTvergaardNeedleman1982StressCriterion.zip](https://github.com/thelfer/tfel/files/9301335/GursonTvergaardNeedleman1982StressCriterion.zip)

**Comment by thelfer** [comment]
@hureje I applied your patch. Would you check the doc ?
