### ISSUE TITLE
[TFEL Windows install] Unable to build the current version on Windows

### ISSUE THREAD

**Issue by jb251061** [thelfer/tfel#278]
Hi,

I've been trying to build and install the current version of TFEL on a Windows laptop (Windows 10 64 bits version 20H2) for a day now and I've been unsuccessful so far. I usually use the version provided with Cast3M but since I want to test out a recent feature I have no choice…
I've tried the several ways suggested on the TFEL website, here are the outcomes:

- **Installation based on cmake and Visual Studio**:

I used Visual Studio 2022 which was already installed on my computer and adapted the script as follows:
`cmake.exe ..\tfel -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release -Dlocal-castem-header=ON -DTFEL_SVN_REVISION=Unknown -DCMAKE_INSTALL_PREFIX=%TFELHOME%`
This quickly yielded some errors like:

>   MathException.cxx
  LUException.cxx
  QRException.cxx
  Discretization1D.cxx
  StensorConcept.cxx
  TensorConcept.cxx
C:\tfel-master\src\tfel\include\TFEL/Math/Tensor/TensorConcept.hxx(126,3): error C2475: 'tfel::math::abs' : redéfinition ; incompatibilité du spécificateur 'constexpr' [C:\tfel-master\src
\build-vs\src\Math\TFELMath.vcxproj]
C:\tfel-master\src\tfel\include\TFEL/Math/Stensor/StensorConcept.hxx(90): message : voir la déclaration de 'tfel::math::abs' [C:\tfel-master\src\build-vs\src\Math\TFELMath.vcxproj]
C:\tfel-master\src\tfel\include\TFEL/Math/Tensor/TensorConcept.hxx(131,3): error C2475: 'tfel::math::trace' : redéfinition ; incompatibilité du spécificateur 'constexpr' [C:\tfel-master\s
rc\build-vs\src\Math\TFELMath.vcxproj]
C:\tfel-master\src\tfel\include\TFEL/Math/Stensor/StensorConcept.hxx(99): message : voir la déclaration de 'tfel::math::trace' [C:\tfel-master\src\build-vs\src\Math\TFELMath.vcxproj]
C:\tfel-master\src\tfel\include\TFEL/Math/Tensor/TensorConcept.hxx(233,3): error C2475: 'tfel::math::computeDeterminantDerivative' : redéfinition ; incompatibilité du spécificateur 'const
expr' [C:\tfel-master\src\build-vs\src\Math\TFELMath.vcxproj]
C:\tfel-master\src\tfel\include\TFEL/Math/Stensor/StensorConcept.hxx(140): message : voir la déclaration de 'tfel::math::computeDeterminantDerivative' [C:\tfel-master\src\build-vs\src\Mat
h\TFELMath.vcxproj]
C:\tfel-master\src\tfel\include\TFEL/Math/Tensor/TensorConcept.ixx(529,3): error C2995: 'enable_if<0,void>::type tfel::math::polar_decomposition(TensorType &,StensorType &,const TensorTyp
e2 &)' : modèle de fonction déjà défini [C:\tfel-master\src\build-vs\src\Math\TFELMath.vcxproj]
C:\tfel-master\src\tfel\include\TFEL/Math/Tensor/TensorConcept.hxx(254): message : voir la déclaration de 'tfel::math::polar_decomposition' [C:\tfel-master\src\build-vs\src\Math\TFELMath.
vcxproj]

I can provide a full log file if needed.
I also tried Visual Studio 2019 which was also already installed but that did not help.

- **Installation based on cmake and MinGW**:

I installed MinGW 12.1.0 on my own since it does not come with Cast3M anymore, as well as cmake 3.24.0. I first tried the win32 version of MinGW, but then I got some errors of the type `error: 'mutex' in namespace 'std' does not name a type`. After a quick search I found out that this could be fixed by using the posix version instead, so I installed that version. I adapted once again the script with the path to mingw and the following line:
`cmake.exe ..\tfel -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -Dlocal-castem-header=ON -DCMAKE_INSTALL_PREFIX=%TFELHOME%`
This time it actually went as far as to build some stuff for a while, which gave me hope. However, problems started occurring when building `ImplicitDSLBase.obj`, and I got the following errors:

> C:\tfel-master\src\tfel\mfront\src\ImplicitDSLBase.cxx: In member function 'virtual void mfront::ImplicitDSLBase::completeVariableDeclaration()':
C:\tfel-master\src\tfel\mfront\src\ImplicitDSLBase.cxx:1247:7: error: 'ushort' was not declared in this scope; did you mean 'short'?
 1247 |       ushort iterMax = 100u;
C:\tfel-master\src\tfel\mfront\src\ImplicitDSLBase.cxx:1251:56: error: 'iterMax' was not declared in this scope
 1251 |       this->mb.setParameterDefaultValue(uh, "iterMax", iterMax);

This time I could not figure out how to solve it. I did try a couple of different MinGW versions just to check (the sjlj and seh versions) but that did not work.

- **Installation based on MSYS2**:

I followed the tutorial from the website with all the `pacman` commands to add the dependencies and this time I was actually able to get it to compile without errors! However, no matter what I did, I could not get mfront.exe to work because it could not find the mfront dll file… I wasn't even able to call `mfront --version`. I tried adding the paths to my .bashrc. as suggested for UNIX systems, but my system still could not pick up the libraries, and I also tried adding them to my Windows path, but that did not work either.

### Final thoughts

On the other hand I was able to install TFEL correctly in WSL. and I was able to run it on my mfront file successfully. However, I do think that it would be nice to have a working solution for Windows because:

1. I am currently working on Cast3M on the Windows side of things, eventhough I have WSL installed;
2. My colleagues work on Windows and don't run WSL. Most of them probably don't even know what that is, so if I want them to eventually use mfront they will need to install it on Windows. I could wait for the next Cast3M release to ship the current mfront features that I need, but the 2022 release barely dropped, so that's not going to be for another year…

Is there anything that you would like me to try? Of course, I am 100% willing to provide any further tests and information to solve this issue.

Sincerely,

Joffrey

**Comment by thelfer** [comment]
Hi @jb251061,

Thanks for this detailled report, this is extremly useful. We currently have continuous integration processes on Mac Os and Linux, but we lack virtual machines for a long time.

Visual Studio is currently not supported by versions greater than 4.0 du to the compiler undecent state regarding modern `C++` template programming.

Concerning MinGW, I don't have access to a windows box right now, but I commited a fix for this problem. Would you try again ?

Concerning MSYS2, I'll give a try ASAP. I can't say what's wrong without further investigations.

Best,
Thomas

**Comment by jb251061** [comment]
Thanks for getting back to me so quickly Thomas!

Your fix did solve the issue, I managed to compile everything correctly :)
However `mfront --version` is complaining that it can't find some sjlj library, which I guess is due to the fact that I used  `MinGW - x86_64-12.1.0-release-posix-sjlj-rt_v10-rev3`. I started the process again with `MinGW - x86_64-8.1.0-release-posix-seh-rt_v6-rev0` to see if that solves the issue.
I'll get back to you as soon as it's over.

**Comment by thelfer** [comment]
@jb251061 Great, we are making progress.

> However mfront --version is complaining that it can't find some sjlj library

Seems like an environment issue. Many projects copy this kind of library in the `bin` directory, along with the executable.

**Comment by jb251061** [comment]
Ok so I confirm that building TFEL with the seh version of MinGW worked, and I get a correct output when I run `mfront --version`.

But I still could not build the behavior I wanted to test, I got:

> callMake: can't build target 'all'
Command was: make.exe -C src -f Makefile.mfront all -s

Then again I do not have a `make.exe` available, I have `mingw32-make.exe` though since I'm using MinGW.
I was able to fix it (at least it would seem), by creating a copy of that executable named `make.exe`. Then I also had to create a `TFELHOME` environment variable, otherwise it did not work. I set it to the install path for TFEL, is that correct?
I don't know if there is a way to avoid all that tinkering but it would be nice :)

At least now I can build the behavior, and all that remains is for me to test it with Cast3M!

Thanks again.

**Comment by thelfer** [comment]
> Then again I do not have a make.exe available 

You can define a `MAKE` variable environment. That will be used by `MFront`. This is what is done the `Cast3M` scripts (don't remember if it is in `compilcast` or in `environnement_Cast3M21`)

> I also had to create a `TFELHOME` environment variable

That is unexpected. I wouldn't expect that to be required. I need to make tests :)

**Comment by jb251061** [comment]
> You can define a `MAKE` variable environment. That will be used by `MFront`. 

Cool, that works and is cleaner than what I did :)

> (don't remember if it is in `compilcast` or in `environnement_Cast3M21`)

I just checked and it's in `environnement_Cast3Mxx` ^^

> That is unexpected. I wouldn't expect that to be required. I need to make tests :)

I had a feeling that it was odd :)

Anyway, I really appreciate the help 👍
