### ISSUE TITLE
Hyperelastic material model (Ogden)

### ISSUE THREAD

**Issue by mrgprasad** [thelfer/tfel#312]
Is the implementation of the Ogden material model in MFront limited to 1st order (p=1)?

**Comment by thelfer** [comment]
@mrgprasad The implementation presented [here](https://thelfer.github.io/tfel/web/ogden.html) is limited to first order. But it is easy to modify it. You shall use it as a basis to implement your own version.

**Comment by mrgprasad** [comment]
Thank you @thelfer.

**Comment by mrgprasad** [comment]
@thelfer Is there a validation test case or an example for the Ogden model implemented in MFront.
I am currently trying to run the model with CodeAster, and need some help with the values for K, mu and alpha.
Thanks

**Comment by thelfer** [comment]
@mrgprasad Sorry, I can't find any.. alpha must be strictly greater than 3 according to the code. Any positive value for K and mu shall work...

**Comment by mrgprasad** [comment]
@thelfer I have set up an example (simple cube being pulled from one side) to test the Ogden model. Ran the simulation, but I can't make sense of the results obtained. Check the results file attached. 
Even for a small applied displacement the model shows very high element distortion. 
In addition, the model displaces along X significantly. 

Note: The same model with Signorini (MFront implementation) works as expected.   
[ogdenTest.zip](https://github.com/thelfer/tfel/files/9632454/ogdenTest.zip)

**Comment by thelfer** [comment]
@mrgprasad Please find attach a simple unixial tensile test based on `MTest`. To make it work, I had to change the eigen solver. Please try it and let me know if everything seems ok in `MTest`. Then we'll have a look at `code_aster`.

[ogdenTest2.zip](https://github.com/thelfer/tfel/files/9633012/ogdenTest2.zip)

**Comment by mrgprasad** [comment]
@thelfer Thanks. Yes, everything works in MTest now.

**Comment by thelfer** [comment]
@mrgprasad Still troubles with `code_aster` ?

**Comment by mrgprasad** [comment]
@thelfer Yes, still having problems
Starting model
![image](https://user-images.githubusercontent.com/26977833/191951487-403b247c-8c76-480a-b7f9-ec7a37bd4c50.png)

This is after the 1st time step
![image](https://user-images.githubusercontent.com/26977833/191951386-0b093f9a-1e5a-4020-bb9e-66d44bd491c7.png)

**Comment by thelfer** [comment]
@mrgprasad would you attach your test with Signorini ?

**Comment by thelfer** [comment]
> Do you have example validation setup for Signorini that works?

Maybe you should have a look at the official tests (which include MFront+aster+GROT_GDEP): https://www.code-aster.org/V2/doc/default/en/man_v/v6/v6.04.187.pdf

**Comment by mrgprasad** [comment]
@thelfer I used the official test example and both Signorini and Ogden models seem to work. Still have no idea where the error is in my simulation setup. Thanks for the tip!!!

Anyways, regarding the Ogden model: 
1. Why must the alpha value be strictly greater than 3?
2. If one extends the model to higher order, then all the alpha values must be greater than 3 also?

**Comment by thelfer** [comment]
@mrgprasad Great !

To be honest, I only had a rapid view on your files. As I am not a regular `code_aster` user, I am not of great help here, unfortunately.

> Why must the alpha value be strictly greater than 3?

I have seen in my implementation that I used x^(alpha-2). Probably to compute the consistent tangent operator, not sure. Anyway, if x is 0, it could lead to a trouble with alpha lower or equalt to 2 (Of course, if x can't be zero, then my remark is just pure non sense). I let you check !

**Comment by thelfer** [comment]
@mrgprasad Is this Issue still relevant ?

**Comment by mrgprasad** [comment]
No, thank you. Will close it.
