### ISSUE TITLE
Material model for Thermoplastics (Polymers)

### ISSUE THREAD

**Issue by mrgprasad** [thelfer/tfel#313]
Hi all, I went through the MFront gallery but could not find any material model that can be used for predicting the behavior Thermoplastics. Traditional metal plasticity or hyperelasticity models are not applicable here. 

Here's some Constitutive model that are relevant for thermoplastics:
1. Three network  model (https://polymerfem.com/polymer_files/Three_Network_Model_2010.pdf)
2. Bergstrom-Boyce model (https://polymerfem.com/polymer_files/BB_cyclic_loading.pdf)

Any comments regarding this is greatly appreciated.

**Comment by thelfer** [comment]
@mrgprasad Never tried such models. The hyperelastic part does not seem that compilated, except that it requires the computation of the inverse of the langevin function and its derivative for the computation of the consistent tangent operator.

Concerning the visco-elastic part, I recently started a tutorial on FeFp decomposition. It is based on the Mandel stress for thermodynamics consideration which might not be equivalent to Tb' in the the Bergstrom-Boyce model.

Do you have a reference implementation ? What solver are you targeting ?

**Comment by mrgprasad** [comment]
@thelfer Thanks for the quick reply. Could you please provide the link to the tutorial? 

I don't have a reference implementation. The solver is **CodeAster**.

**Comment by thelfer** [comment]
@mrgprasad This tutorial is not ready yet. Here is a draft:  [FeFpImplicitPlasticity.zip](https://github.com/thelfer/tfel/files/9503406/FeFpImplicitPlasticity.zip)

With this, and if we accept to fit in the framework described in this tutorial, the main difficulty seems the hyperelastic law, and in particular the computation of the inverse Langevin function...

**Comment by mrgprasad** [comment]
@thelfer I found a paper discussing the algorithmic implementation for the Begstrom-Boyce model:
1. https://www.researchgate.net/publication/225224524_Bergstrom-Boyce_model_for_nonlinear_finite_rubber_viscoelasticity_Theoretical_aspects_and_algorithmic_treatment_for_the_FE_method
2. Finite element formulation for modeling nonlinear viscoelastic elastomers (section 3.3)

Will these be of help for the MFront implementation?

Also, I found a python implementation for calculating Inverse of the langevin function (https://github.com/DamianRMusk/Python_BB_Biomaterials/blob/main/BB_Biomaterials.py)

**Comment by thelfer** [comment]
@mrgprasad Various implementations of the inverse of the Langevin function have been implemented, see https://thelfer.github.io/tfel/web/tfel-material.html#computation-of-the-inverse-of-the-langevin-function for details

**Comment by thelfer** [comment]
> So, the steps are:
> 
> 1. Implement the inverse Langevin function (See Issue [[tfel-material] Implement the inverse Langevin function #314](https://github.com/thelfer/tfel/issues/314)).
> 2. Implement the Arruda-Boyce in the Lagrangian frame-work (i.e. using the right Cauchy tensor and PK2). This step is fairly easy after Step 1.
> 3. Implement the viscous part.
> 
> I can help for the implementation (in particular for Step 1), but you'll have to test it. Are you willing to ?
> 
> Best,
> 
> Thomas

@mrgprasad up ?

**Comment by thelfer** [comment]
@mrgprasad I close the issue. Do no hesitate to reopen it when you'll be ready.
