### ISSUE TITLE
Compile Error: No match for 'operator<<'

### ISSUE THREAD

**Issue by jonathonmckay** [thelfer/tfel#315]
I am trying to compile an older version of tfel which was included in a Code-Aster package. Tfel version is 3.2.1. Part way through the compile process, I get a pile of errors like this:
```[ 29%] Building CXX object mfront/src/CMakeFiles/TFELMFront.dir/NewtonRaphsonSolvers.o
/tmp/install_tfel.15082/tfel-3.2.1/mfront/src/NewtonRaphsonSolvers.cxx: In member function ‘virtual void mfront::MFrontNewtonRaphsonSolverBase::writeResolutionAlgorithm(std::ostream&, const mfront::BehaviourDescription&, mfront::MFrontNewtonRaphsonSolverBase::Hypothesis) const’:
/tmp/install_tfel.15082/tfel-3.2.1/mfront/src/NewtonRaphsonSolvers.cxx:112:11: error: no match for ‘operator<<’ (operand types are ‘std::ostream’ {aka ‘std::basic_ostream<char>’} and ‘const char [9]’)
  112 |       out << "tmatrix<" << n2 << "," << n2 << ",real> njacobian;\n";
      |       ~~~ ^~ ~~~~~~~~~~
      |       |      |
      |       |      const char [9]
      |       std::ostream {aka std::basic_ostream<char>}
```

I have searched high and low for a solution, but all fixes I've found have involved changing the code. Is there a compiler flag or something I'm missing?

Details:
- OS: CentOS 7.5
- GCC: 10.1.0

**Comment by thelfer** [comment]
@jonathonmckay It seems like the header `TFEL/Math/Matrix/tmatrixIO.hxx` is missing.

If I may, have shall better give the `rliv-3.2` a try which is still maintained and contains only bug fixes.

**Comment by jonathonmckay** [comment]
Hey @thelfer , thanks for getting back to me so quickly.

For ostream, do you mean the ostream that's part of the OS, or the one that comes with Boost? I thought there was an issue with my install of Boost, so I went and got a new one and re-built it, but I'm getting the same errors.

For `rliv`, I'm sorry, I don't know what that is. Do you mean a newer version of tfel-3.2.x? (I did notice there were newer versions of old versions, as it were.) The version of tfel I have came packages with Aster, so I don't really want to swap it out, don't know what that will do to Aster's confusing setup scripts, if I can avoid it.

**Comment by thelfer** [comment]
> For ostream, do you mean the ostream that's part of the OS, or the one that comes with Boost? I thought there was an issue with my install of Boost, so I went and got a new one and re-built it, but I'm getting the same errors.

Sorry, I meant the standard `<ostream>` header

> For `rliv`, I'm sorry, I don't know what that is.

Every major version X.Y is associated with a `rliv-X.Y` branch where bugs are fixed from which minor versions are generated. 
For version `3.2.0`, see: <https://github.com/thelfer/tfel/tree/rliv-3.2>

> The version of tfel I have came packages with Aster, so I don't really want to swap it out, don't know what that will do to Aster's confusing setup scripts, if I can avoid it.

So, the only thing that you can do is take the sources delivered with `code_aster`, unpack them, try to compile them, fix the files in the sources and compress the corrected sources. For corrections, you can browse the `rliv-3.2` sources. For example, for the `NewtonRaphsonSolvers.cxx`, you can check this corrected version: <https://github.com/thelfer/tfel/blob/rliv-3.2/mfront/src/NewtonRaphsonSolvers.cxx>. Note that the first included header is indeed `<ostream>` in the corrected version

**Comment by jonathonmckay** [comment]
Ahh, I see what you mean now. On line 14 of https://github.com/thelfer/tfel/blob/rliv-3.2/mfront/src/NewtonRaphsonSolvers.cxx is:
```#include <ostream>```
This line is missing from the version included with Aster.
I'll see what I can do by cherry-picking files from the fixed version.

**Comment by thelfer** [comment]
@jonathonmckay That's exactly the point. As I told you, version 3.2.1 used to compile with every versions of `gcc` available when it was released (and `clang`, `intel` and `microsofts` compilers too). The change in their implementation of the standard library came afterwards.

That's annoying, but nothing that I could avoid...

**Comment by jonathonmckay** [comment]
Thank you very much for the help and explanation.
I decided to use the whole fixed version. The build finished fine. Now I have to see if I can convince that other package to see this version. But that's my problem.

**Comment by thelfer** [comment]
One ugly trick that shall work: 

1. change the version number at the top of the CMakeLists.txt file:
    ```cmake
    #major and minor version
    tfel_project(4 1 "0-dev")
    ```
2. rename the source directory to match the one of Version 3.2.1
3. compress it with the name of tar file of Version 3.2.1
4. Build `code_aster` as usual

**Comment by jonathonmckay** [comment]
Thank you again.
I'll give that a shot when I get to that point.

**Comment by jonathonmckay** [comment]
I managed to fool aster.
The trick was to run the setup script for aster until it broke, then change the version number of Tfel as you suggested, build and install tfel exactly by hand how the aster script wanted it, then run the aster script again. The aster script saw tfel installed, and skipped it.
Thank you again for all your help.

**Comment by jonathonmckay** [comment]
For further reference, it seems other users of Code Aster are having the same problem.
(https://code-aster.org/forum2/viewtopic.php?id=26422)
