### ISSUE TITLE
[mfront] Automatic declaration of  climb tensors

### ISSUE THREAD

**Issue by Narquoistel** [thelfer/tfel#317]
Pour décrire la montée en plasticité cristalline, il serait bon d'avoir le tenseur n_s\otimes n_s

**Comment by thelfer** [comment]
@Narquoistel Tu as une préférence pour le nom de la variable associée ?

**Comment by thelfer** [comment]
## Generation of climb tensors

For a given slip system of normal \(\vec{n}\), the climb tensor is defined as \(\vec{n}\,\otimes\vec{n}\).

If sliding systems are declared, `MFront` generates a class containing the definition of all normals, slip directions, orientation tensors (see [this page](singlecrystal.html) for details).

This class now contains the climb tensors:

- The climb tensors of all slip systems are stored in a variable named `climb_tensors`
- The climb tensors all the `i`th family of slip systems' is stored in a variable named `climb_tensors`i, i.e. `climb_tensors0`, `climb_tensors1`, etc....

> **Note**
> 
> In previous versions of `MFront`, climb tensors could have been computed using the normals using `buildFromVectorDiadicProduct` method from the `stensor` class.

## Getting information about the climb tensors in `mfront-query`

The following queries are available to retrieve information about climb tensors:

- `--climb-tensors`: list all the climb tensors, sorted by family".
- `--climb-tensors-by-index`: list all the climb tensors.
- `--climb-tensors-by-slip-system`: list all the climb tensors sorted by slip systems.
