### ISSUE TITLE
mtest python binding: invalide interface 'Python'

### ISSUE THREAD

**Issue by leopeuziat** [thelfer/tfel#336]
I compile a MaterialLaw with interface = python. I want to use the .so with mtest python binding:
`prop = mtest.MaterialProperty(library_path,property_name)`
I get the error:
`RuntimeError: MaterialProperty::getMaterialProperty: invalid interface 'Python'`

Configuration: master branch from github, commit ad85da9a3c19ddb19c82b75b8290c2937d4b85c0 from 2022/08/22

**Comment by thelfer** [comment]
@leopeuziat `MTest` can't handle material properties generated with the `python` interface. That would require embedding the whole `python` library and create cumbersome wrappers. The same limitation applies to the `octave` interface for example.

The only interfaces supported by the `mtest.MaterialProperty` class are: `castem`, `cyrano` and `generic`
