### ISSUE TITLE
How to combine StandardElastoViscoPlasticityBrick with external model for AuxiliaryStateVariables

### ISSUE THREAD

**Issue by DrAkustik** [thelfer/tfel#338]
I am trying to implement the ANAND model (description can be found [here](https://doc.comsol.com/5.5/doc/com.comsol.help.sme/sme_ug_theory.06.32.html)) for code_aster with MFRONT.

My first attempt was to use the StandardElastoViscoPlasticityBrick in combination with the HyperbolicSine inelastic_flow and an AuxiliaryStateVariable for the deformation resistance (variable s_a in the link above). However, I get an error message:

`BehaviourDescription::getMaterialPropertyInputCategory: only auxiliary state variable computed by a model are allowed here`

Is there an example how to write a model for a state variable and how to include it in the StandardElastoViscoPlasticityBrick?
I found the [information](https://tfel.sourceforge.net/models.html) about models. However, I don't know how to incorporate such a model into the StandardElastoViscoPlasticityBrick.

**Comment by thelfer** [comment]
Dear @DrAkustik,

Basically, you can't implement this model with the `StandardElastoViscoPlasticity` brick.  The brick must know all the equations driving all the internal state variables to derive suitable implicit equations are derivatives. Your equation is simply not supported yet.

The message says that you have one coefficient depending on an auxiliary state variable which is not computed by a model. To understand this message, you must know the role of models. Models are meant to describe the evolution of a set of internal state variables, but this evolution must be independent of the mechanical state. For example, you can use models to compute the swelling of materials du to change in relative humidity, fission products, and phase transition driven by the change in temperature. 

As the evolutio of the deformation resitance is  strongly coupled with the mechanical evolution, models can't be used.

So the only thing that you can do is too rely on the `StandardElasticity` brick and write the implicit system by yourself. You may want to read this tutorial as a starting point: https://thelfer.github.io/tfel/web/isotropicplasticityamstrongfrederickinematichardening.html or https://thelfer.github.io/tfel/web/orthotropiclinearhardeningplasticity.html.

Please find attached an MFront file that I wrote rapidely to help you get started : [AnandViscoplasticBehaviour.zip](https://github.com/thelfer/tfel/files/9893758/AnandViscoplasticBehaviour.zip)

The trick here is to introduce an integration variable corresponding to the deformation resistance scaled by the Young's modulus so that every variables and residuals in the implicit scheme have the same order of magnitude. You must also deal with care the fact that the equation driving the evolution of the deformation resistance is ill-formed if Fcr is zero (which happens if the stress is zero, which usually happens at the first iteration of the first time step)

Do not hesitate to ask for help.

**Comment by DrAkustik** [comment]
Thank you, Thomas, for your quick and detailed response! The first link and your MFront file helped a lot to understand how to write an MFront file with the Implicit DSL.

I have a question regarding the AuxiliaryStateVariable in your example:
As far as I understand this AuxiliaryStateVariable is only required for outputting the unscaled variable sa and the scaled IntegrationVariable s is used within the Integrator. Am I right?

I tried to implement the Anand model based on your example: [AnandViscoplasticBehaviour.zip](https://github.com/thelfer/tfel/files/9896218/AnandViscoplasticBehaviour.zip)
To solve the problem of the ill-formed evolution equation, I used the max function as used in calculating iseq.

I also wrote an MTest file and a Python file which are intended to reproduce this [figure](https://www.semanticscholar.org/paper/Determination-of-Anand-constants-for-SAC-solders-or-Motalab-Cai/c07bbfdd21530baaab7782024a9290df8cfd3e4b/figure/12) with these [parameters](https://www.semanticscholar.org/paper/Determination-of-Anand-constants-for-SAC-solders-or-Motalab-Cai/c07bbfdd21530baaab7782024a9290df8cfd3e4b/figure/11). However, my result (subplot 1, stress-strain curve) looks quite different. I also plotted p and sa. The orange line in the second subplot is the elastic strain. 

Do you have an idea, what I did wrong?

**Comment by thelfer** [comment]
> As far as I understand this AuxiliaryStateVariable is only required for outputting the unscaled variable sa and the scaled IntegrationVariable s is used within the Integrator. Am I right?

Exactly:

- integration variables are part of the implicit system but not saved for one time step to the other
- state variables  are part of the implicit system and saved for one time step to the other
- auxiliary state variables are not part of the implicit system but saved for one time step to the other

**Comment by thelfer** [comment]
> Do you have an idea, what I did wrong?

The `@InitLocalVariables` code block is highly dubious.  This code is called every time the behaviour integration is called. Here you reset your internal state variables again and again to a fixed value. Probably not was you want.

This code block shall initialize `s` (which is not saved) from `sa` (which is saved).

The initial value of `sa` shall be set in `MTest` using the `@InternalStateVariable` keyword. See:

```bash
$ mtest --help-keyword=@InternalStateVariable
```

for details

**Comment by DrAkustik** [comment]
Thank you very much! It was indeed not clear to me, that the @InitLocalVariables inits the variables every integration step. Now everything works fine!

How can the @InternalStateVariable be initialized when used inside a finite element solver like code_aster? I know how to set the Parameters, but this initialization is not clear to me.

Will providing the Jacobian analytically decrease the computation time of a finite element solver or is it even mandatory? Is there something else to consider, when using such an MFront behaviour in code_aster?

**Comment by thelfer** [comment]
> Now everything works fine!

Great !

> How can the @InternalStateVariable be initialized when used inside a finite element solver like code_aster?

The syntax does depend on the code. I don't remember the syntax in code_aster. What you can also do is to shift the values in MFront by the initial value and use the fact that all FEM code initializes the state variables to zero. That's a trick, but it is a common workaround.

> Will providing the Jacobian analytically decrease the computation time of a finite element solver or is it even mandatory?

It is not mandatory, but it does decrease the computational time (significantly in most cases).

> Is there something else to consider, when using such an MFront behaviour in code_aster?

Depends. Would you use finite strain modelling ?

**Comment by DrAkustik** [comment]
Yesterday I tried to use the MFRONT model in code_aster. However, code_aster (a single hexaeder model) stops in the first iteration with a convergence problem. There were no convergence problems when testing with MTEST.

Thus, I removed the ANAND equations from the MFRONT library for testing:

`const auto s_ = s + theta * ds;`
`feel = deel - deto;`
`fp = dp;`
`fs = ds;`

With MTEST I get a linear stress strain relationship. However, code_aster stops with a convergence problem in the first iteration. Thus, the convergence problem seems not to be related to my anand implementation. Do you have a suggestion what I am doing wrong? This is my code_aster comm-file: [Stage_1.zip](https://github.com/thelfer/tfel/files/9919578/Stage_1.zip)

Finite strain modelling would be the next step.

**Comment by thelfer** [comment]
I am not a regular `code_aster`, so I will probably miss the point, but:

1. You define an istropic material for the reference material (`ELAS=_F(E=46000.0, NU=0.3)`)
2. You did no define the rotation matrix or the material frame. 

You would first check my script with the native orthotropic elastic behaviour of `code_aster`

Note that there are several tests to check how that MFront orthotropic behaviours works well with `code_aster`. See https://code-aster.org/V2/doc/v11/fr/man_v/v1/v1.03.128.pdf 

> Finite strain modelling would be the next step.

You already are doing a finite strain modelling (See the line `DEFORMATION='GDEF_LOG'`)

**Comment by thelfer** [comment]
I am not a regular `code_aster`, so I will probably miss the point, but:

1. You define an istropic material for the reference material (`ELAS=_F(E=46000.0, NU=0.3)`)
2. You did no define the rotation matrix or the material frame. 

You would first check my script with the native orthotropic elastic behaviour of `code_aster`

Note that there are several tests to check how that MFront orthotropic behaviours works well with `code_aster`. See https://code-aster.org/V2/doc/v11/fr/man_v/v1/v1.03.128.pdf 

> Finite strain modelling would be the next step.

You already are doing a finite strain modelling (See the line `DEFORMATION='GDEF_LOG'`)

**Comment by DrAkustik** [comment]
Changing the lines

`@Brick StandardElasticity{`
`  young_modulus : 46000,`
`  poisson_ratio : 0.3`
`};`

to

`@Brick StandardElasticity;`
`@MaterialProperty stress young;`
`young.setGlossaryName("YoungModulus");`
`@MaterialProperty real nu;`
`nu.setGlossaryName("PoissonRatio");`

seems to fix the problem. Now I can pass the young's modulus and the poisson's ratio from code_aster to MFRONT followed by the ANAND parameters and the calculation converges.

I assume it is not possible to pass the two parameters to MFRONT with the first implementation?

**Comment by thelfer** [comment]
@DrAkustik I must apologize. I made a confusion with another thread which was about an orthotropic material. Sorry for the confusion.

Concerning your troubles, there indeed seems to be something very nasty in `code_aster` regarding the definition of the elastic properties.... And self-contained behaviours (i.e. behaviours with no material properties, only parameters) does not (always) work as expected. The trouble is that `code_aster` does not produce an error and just "do not converge" which is very painful...

**Comment by thelfer** [comment]
@DrAkustik Is this issue still relevant ?

**Comment by DrAkustik** [comment]
I've been testing the material behaviour in code_aster for the last few weeks and it works fine. MFRONT is a great tool.

**Comment by thelfer** [comment]
@DrAkustik Thanks for the feed-back. Do not hesitate to share your results if relevant.
Best,
Thomas
