### ISSUE TITLE
Append code to `@TagentOperator` block for an `ImplicitFiniteStrain` behaviour

### ISSUE THREAD

**Issue by jeanmichelscherer** [thelfer/tfel#341]
Hi @thelfer,

In the attached file below, I would like to multiply a float (for instance here a degradation function) with the tangent operator which is automatically computed. In the present state, the compilation fails with the following error, although I included `Append` in the options:
```
Error while treating file 'FCCMericCailletaudFiniteStrainSingleCrystalViscoPlasticity.mfront'
BehaviourData::setCode: a code block named 'ComputeTangentOperator-DTAU_DDF' already exists.
If you wanted to append this new code to the existing one, you shall use the 'Append' option.
You can also replace it with 'Replace' option (assuming you know what you are doing).
```
I also noticed that if I try to do that operation in another block instead, for instance the `@UpdateAuxiliaryStateVariables` block, then, the compilation fails because the `*` operator is not defined between a `double` and a `TangentOperator`.

Do you know how I could add lines to the `@TagentOperator` block and do that kind of operation?

[FCCMericCailletaudFiniteStrainSingleCrystalViscoPlasticity.tar.gz](https://github.com/thelfer/tfel/files/10027345/FCCMericCailletaudFiniteStrainSingleCrystalViscoPlasticity.tar.gz)

**Comment by thelfer** [comment]
Hi @jeanmichelscherer ,

I don't understand your code: the Mandel stress is not affected by damage ???
Furthermore, you probably want to use the damage at the end of the time step: `damage+ddamage`.

Here are two solutions (IMHO):

## First solution (ugly)

```cpp
@InitLocalVariables {
  const auto damage_ets = damage + ddamage;
  const auto gd = power<2>(1-damage_ets) + kres;
  D *= gd;
}
```

## Second solution (better)

```cpp
@Brick FiniteStrainSingleCrystal{
  young_modulus1 : '((1-damage)*(1-damage)+kres)*1'., //208000,
  young_modulus2 : '((1-damage)*(1-damage)+kres)*1'., //208000,
  young_modulus3 : '((1-damage)*(1-damage)+kres)*1'., //208000,
  poisson_ratio12 : 0.3,
  poisson_ratio23 : 0.3,
  poisson_ratio13 : 0.3,
  shear_modulus12 : '((1-damage)*(1-damage)+kres)*0.384615384615385', //80000,
  shear_modulus23 : '((1-damage)*(1-damage)+kres)*0.384615384615385', //80000,
  shear_modulus13 : '((1-damage)*(1-damage)+kres)*0.384615384615385', //80000
  shifted_elastic_deformation_gradient : true
};
```

In this case, MFront evaluates the damage at the middle of the time or a the end of the time depending on the context !

**Comment by thelfer** [comment]
I though that there was something like this hidden. This is the kind of things that it is better explicit. Think of the poor guy (can be yourself) that will read your code in a year or two !

**Comment by thelfer** [comment]
@jeanmichelscherer Is this issue still relevant ?

**Comment by jeanmichelscherer** [comment]
It can be closed, thanks.
