### ISSUE TITLE
Adding a custom CrystalStructure for user-defined `SlipSystems`

### ISSUE THREAD

**Issue by jeanmichelscherer** [thelfer/tfel#342]
Hi @thelfer,

Currently supported crystal structures in `Mfront` are cubic, BCC, FCC and HCP.
I would like to implement a custom `CrystalStructure` that lets the user define its own slip systems in the `.mfront` file.
The main reason I want to do that is because I would like to artificially enforce single slip (only one system active). I can already get single slip by setting different yield stresses on the different systems of an FCC crystal for instance, but it is a bit messy since many integration variables are simply not used.

Could you tell me what files I need to modify to set up such a custom `CrystalStructure`?

**Comment by thelfer** [comment]
In this case, I would simply define this slip system by hand !
The `@SlidingSystem` keyword is only meant to generate all the slip systems by symmetry. If you don't need that, don't use it.
What I would do it that I would generate a code with  `@SlidingSystem`  and extract the definition of the orientation tensor of interest.

**Comment by jeanmichelscherer** [comment]
Ok, that makes more sense, thanks.

**Comment by thelfer** [comment]
@jeanmichelscherer Is this issue still relevant ?

**Comment by jeanmichelscherer** [comment]
No, we can close it. Thanks @thelfer.
