### ISSUE TITLE
[mfront] modification of the Gurson-Tvergaard-Needleman stress criterion

### ISSUE THREAD

**Issue by hureje** [thelfer/tfel#356]
The Gurson-Tvergaard-Needleman stress criterion has been implemented using q_1, q_2 and q_3 parameters. The physical meaning of q_3 different from q_1^2 is doubtful. Moreover, the current implementation is not correct for q_3 > q_1^2. 

It is thus proposed to remove the parameter q_3 and replace it by q_1^2, which is done is the attached files. The documentation should be updated as well.
[updateGTN.zip](https://github.com/thelfer/tfel/files/10381342/updateGTN.zip)

**Comment by thelfer** [comment]
@hureje What if we define "q_3 = q_1^2" in the StandardElastoViscoplasticity brick by default and not change the rest of the code ?

**Comment by hureje** [comment]
I think it is safer to remove this parameter to avoid troubles in the future

**Comment by thelfer** [comment]
@hureje Well, I already made the changes. I updated the documentation to say that "q_3 = q_1^2" shall be equal and that this is the default choice. I
