### ISSUE TITLE
[mfront] Index error with interface cyrano, orthotropic behaviour and require stiffness tensor

### ISSUE THREAD

**Issue by GuillotDeltacad** [thelfer/tfel#358]
An index error is identified with the interface cyrano when a behaviour law contain :
  - @OrthotropicBehaviour
  - @RequireStiffnessTensor

The problem can be reproduced with the attached sample:
  Sample_cyrano_ortho_requireS.txt (extension file to converted into mfront)

mfront --interface=cyrano Sample_cyrano_ortho_requireS.mfront

Into the file:  include/TFEL/Material/ortho_requireSBehaviourData.hxx
at line 179-191 (with MFront V3.4.0), elastic material properties are index from -7 to -2 instead of -6 to -1.

             ____________________
 ortho_requireSBehaviourData(const Type* const CYRANOT_,const Type* const CYRANOmat,
const Type* const CYRANOint_vars
,const Type* const)
: young1(CYRANOmat[-7]),
young2(CYRANOmat[-6]),
young3(CYRANOmat[-5]),
nu12(CYRANOmat[-4]),
nu13(CYRANOmat[-2]),
nu23(CYRANOmat[-3]),
[Sample_cyrano_ortho_requireS.txt](https://github.com/thelfer/tfel/files/10400263/Sample_cyrano_ortho_requireS.txt)

eel(&CYRANOint_vars[0]),
T(*CYRANOT_)
{
}
             ____________________

The problem is also present with MFront V4.0.

Best regards,

**Comment by thelfer** [comment]
@GuillotDeltacad Thanks for reporting. This bug has been introduced in TFEL-3.2 when trying to refactor duplicated codes. It is now fixed in all rliv branches.
