### ISSUE TITLE
Add documentation  @UMAT

### ISSUE THREAD

**Issue by LionelGelebart** [thelfer/tfel#376]
As discussed by mail with TH, need documentation for 
@UMATUseTimeSubStepping[umat] true;
@UMATMaximumSubStepping 10;

**Comment by thelfer** [comment]
The webpage describing the `Cast3M` interface has been updated (https://thelfer.github.io/tfel/web/castem.html) with the following information.

## Keywords specific to the `Cast3M` interface

The following keywords are specific to the `Cast3M` interface:

- `@CastemGenerateMTestFileOnFailure` (or  `@UMATGenerateMTestFileOnFailure`). This keyword is followed by a boolean. If this boolean is true, the behaviour will generate a `MTest` file for every integration failure. This keyword is deprecated in favor of `@GenerateMTestFileOnFailure`.
- `@CastemUseTimeSubStepping` (or `@UMATUseTimeSubStepping`). This keyword is followed by a boolean. If this boolean is true, a local substepping scheme is set up. The time step is reduced by a factor \(2\) at each sub steps. This time step is never increased.
- `@CastemMaximumSubStepping` (or `@UMATMaximumSubStepping`). This keyword is followed by a strictly positive integer which indicates the maximum number of sub steps allowed. Any value greater that \(5\) is not reasonnable, as it would lead to reduction by a factor of at most \(2^{5}\) (i.e. \(32\)) of the initial time step.
- `@CastemDoSubSteppingOnInvalidResults` (or `@UMATDoSubSteppingOnInvalidResults`). This keyword is followed by a  boolean. If true, invalid results will lead to a sub step. By default, invalid results does not lead to a substeps. Invalid results are dubious results according to user defined criteria in the `@APosterioriTimeStepScalingFactor` code block.
- `@CastemFiniteStrainStrategy` (or `@UMATFiniteStrainStrategy`). This keyword is followed by a string. This keyword is only valid for strain-based behaviours. Valid values are `None`, `FiniteRotationSmallStrain`, `MieheApelLambrechtLogarithmicStrain` and  `LogarithmicStrain1D`. This keyword is deprecated in favor of the  `@StrainMeasure` keyword.
- `@CastemFiniteStrainStrategies` (or `@UMATFiniteStrainStrategies`). This keyword is followed by a list of strings (see the documentation  of the `@CastemFiniteStrainStrategy` keyword). A version of the  behaviour will be generated for each strategy defined. This keyword is  deprecated in favor of the `@StrainMeasure` keyword.
