### ISSUE TITLE
Reg. writing an MFront code for an plasticity model

### ISSUE THREAD

**Issue by pavanbhukya** [thelfer/tfel#377]
Dear Sir,

I am Pavan, a Ph.D. student from India. I recently started using OpenGeoSys for my modelling works. At the same time, I learned that the constitutive framework of the material code I am looking for is adopted in OGS and is one of the codes developed in MFront.
 
The material code I am planning to modify is the Modified Cam Clay (MCC) model. The current MFront file of MCC is modified to include the cementation effects as per [Gai and Sanchez, 2019](https://www.researchgate.net/publication/328206533_An_elastoplastic_mechanical_constitutive_model_for_microbially_mediated_cemented_soils). Therefore, I have some additional hardening variables that need to be incorporated into the MCC mfront file.

I have derived the partial derivates for the required model similar to the [MCC case](https://thelfer.github.io/MFrontGallery/web/SemiImplicitModifiedCamClay_OpenGeoSys2020.html). I have acquired the partial derivative equations for forming a new jacobian matrix in the material code. However, I need your support in building the mfront file. I need clarification about forming a jacobian matrix because I have some extra additional derivatives that need to be included. I wonder how the code will extract those derivatives to build a jacobian.

I would be very thankful if the TFEL/MFront team could support my research. 

Thanks
Pavan

**Comment by thelfer** [comment]
Dear @pavanbhukya,

The blocks of the jacobian are automatically defined from the definition of the integration variables (which include the state variables). For instance, if you have two variables a and b, then dfa_ddb is automatically defined....

Thomas

**Comment by thelfer** [comment]
I closed the issue because it is more a discussion than an issue
