### ISSUE TITLE
Reg. a nonlinear bulk modulus 

### ISSUE THREAD

**Issue by pavanbhukya** [thelfer/tfel#391]
Dear Thomas,

I am using MFront as a part of the OGS code. I want to give a non-linear bulk modulus as a function of the mean stress (p) and another AuxiliaryStateVariable called pore number (e).

K =((1 + e)/κ)*p
where κ is the constant.

I am trying to modify the modified cam clay implementation given [on your site](https://thelfer.github.io/MFrontGallery/web/SemiImplicitModifiedCamClay_OpenGeoSys2020.html) to include nonlinear elasticity.

I would be glad if you could help me in this regard.

Thanks
Pavan

**Comment by thelfer** [comment]
Dear Pavan,

The main change is that you can't rely on the `StandardElasticity` brick anymore, whether to compute the stress and the tangent operator.

After removing the line `@Brick StandardElasticity;`, you need to:

- Introduce a `@ComputeStress` block.
- Add `deto` to the residual feel
- Introduce a `@TangentOperator` block

As I first step, I strongly recommend you to consider a linear isotropic elastic behavior to check that you have exactly the same results that with the initial implementation. You may have a look at this example and copy/paste the appropriate blocks: https://github.com/thelfer/tfel/blob/master/mfront/tests/behaviours/ImplicitNorton.mfront

Once done, we will discuss the next step, would you ?

**Comment by pavanbhukya** [comment]
Dear Thomas,

As I removed `StandardElasticity`, I am getting an error of unknown D tensor while compiling.

However, I tried forming the D tensor as follows.

`constexpr const auto D = ((lambda+(2*mu/3))*(id2^id2))+(2*mu*(id2-((id2^id2)/3)))`

Still, the error persists.

Please let me know the issue and how to resolve it.

Thanks
Pavan.

**Comment by thelfer** [comment]
Indeed, D used to be defined by the `StandardElasticity` brick. Would you share your code ?

**Comment by pavanbhukya** [comment]
Dear Thomas,

Thanks for the prompt response. I've attached the code for you.

Thanks
Pavan


[ModCamClay_semiExplParaInit_Nonlinear.mfront.zip](https://github.com/thelfer/tfel/files/11418388/ModCamClay_semiExplParaInit_Nonlinear.mfront.zip)

**Comment by thelfer** [comment]
Here is a corrected version
[ModCamClay_semiExplParaInit_Nonlinear.zip](https://github.com/thelfer/tfel/files/11418498/ModCamClay_semiExplParaInit_Nonlinear.zip)

**Comment by pavanbhukya** [comment]
Dear Thomas,

I cannot run the modified code for linear elasticity for longer time steps for the specific problem (triaxial drained test) in OGS.

![image](https://user-images.githubusercontent.com/105070006/236755255-a9b9c4ea-a38d-41bc-b814-95321cb7f7b3.png)

Whereas, with `StandardElasticity` brick, I could run longer.

![image](https://user-images.githubusercontent.com/105070006/236755695-bec98f14-73b8-4364-943b-022378fbb252.png)

Please let me know what the issue might be.

Thanks
Pavan.

**Comment by thelfer** [comment]
You did not take all my remarks in to account. You shall add `-deto` to the residual `feel`. See the attached file:
[ModCamClay_semiExplParaInit_Nonlinear2.zip](https://github.com/thelfer/tfel/files/11419339/ModCamClay_semiExplParaInit_Nonlinear2.zip)

**Comment by pavanbhukya** [comment]
Dear Thomas,

I am very sorry, I forgot to include it. Anyhow, now it worked. Please let me know the next step for including nonlinear bulk modulus.

Thanks
Pavan.

**Comment by thelfer** [comment]
For the next step, you need to change the `@ComputeStress`.
You may find important information in this discussion: https://github.com/thelfer/tfel/discussions/93

**Comment by pavanbhukya** [comment]
Dear Thomas,

Thanks for providing the earlier discussion link.

I have tried incorporating the `NonLinearElasticity` code block into the MCC code.

However, in this case, '@InitLocalVariables` are defined earlier with the lame's constants. But, the `@ComputeStress` block is defined later, which has the elastic constants. This resulted in an error while compiling. Also, the compilation error says `‘De’ was not declared in this scope`.

Please let me know how to resolve these issues.

I am also attaching my code for your reference.

Thanks
Pavan.

[ModCamClay_semiExplParaInit_Nonlinear_New.zip](https://github.com/thelfer/tfel/files/11427418/ModCamClay_semiExplParaInit_Nonlinear_New.zip)

**Comment by thelfer** [comment]
Please find attached a corrected version. But you need to modify the computation of the elastic prediction !
[ModCamClay_semiExplParaInit_Nonlinear_New_TH.zip](https://github.com/thelfer/tfel/files/11429768/ModCamClay_semiExplParaInit_Nonlinear_New_TH.zip)

**Comment by pavanbhukya** [comment]
Dear Thomas,

I have modified the elastic prediction as

`const auto sig_el = lambdax * trace(eel_tr) * Stensor::Id() + 2 * mux * eel_tr`

where `lambdax `and `mux `are Lame's constants updated from `@ComputeStress` block.

The code was compiled successfully. But I couldn't run the code for longer time steps.

Let me know the issues.

Thanks
Pavan

[ModCamClay_semiExplParaInit_Nonlinear_New_TH.zip](https://github.com/thelfer/tfel/files/11438914/ModCamClay_semiExplParaInit_Nonlinear_New_TH.zip)

**Comment by thelfer** [comment]
See this page: https://thelfer.github.io/tfel/web/implicit-dsl.html

`@InitLocalVariables` is called once prior to `@ComputeStress`, so your code is probably wrong.

**Comment by pavanbhukya** [comment]
Dear Thomas,

I couldn't find a way to update the nonlinear bulk modulus in the elastic prediction step explicitly.

However, I managed to use the initial Youngs modulus for the elastic prediction, but it resulted in a linear response again.

Let me know the ways to write the elastic prediction step using nonlinear K.

Thanks
Pavan.

[ModCamClay_semiExplParaInit_Nonlinear_New_TH.zip](https://github.com/thelfer/tfel/files/11442587/ModCamClay_semiExplParaInit_Nonlinear_New_TH.zip)

**Comment by thelfer** [comment]
If computing the elastic prediction is too complicated, you could try something different. You could simply introduce a boolean variable which is true on case of plastic loading and false otherwise. You could select one case *a priori* and use the `@AdditionalConvergenceChecks` code block to check if this hypothesis is consistent, and restart the integration with the other assumption otherwise. See this page for details: https://thelfer.github.io/tfel/web/drucker-prager-cap.html#a-posterio-checks-validation-of-the-assumptions

**Comment by pavanbhukya** [comment]
Dear @cbsilver

I am trying to include nonlinearity in the MCC code. I had a discussion with Thomas in this thread.

I have gone through your earlier discussion on this forum #93 

Please let me know if you could help,

Thanks
Pavan.

**Comment by pavanbhukya** [comment]
Dear Thomas,

How to define a second-order tensor in .mfront file?

Id = {2/3,1,1;1,2/3,1;1,1,2/3}

Thanks
Pavan.

**Comment by thelfer** [comment]
For the moement, you can't initialize variables while declaring them (which only makes sense for the local variables BTW).

`tensor<3,3>` is not a valid syntax. You may want to read those pages: https://thelfer.github.io/tfel/web/tensors.html (in particular Section 1.5.2.1) and https://thelfer.github.io/tfel/web/mfront-types.html for details.

You probably want to do something like this:

```c++
@LocalVariable tfel::math::Stensor4 K;

....

@InitLocalVariables{
   K = Stensor4::K();
}
```

**Comment by pavanbhukya** [comment]
Dear @thelfer 

I got the following error while building. What does this signify?

![image](https://github.com/thelfer/tfel/assets/105070006/735bdd5d-34cd-42f1-9f1d-9265db3be43b)

**Comment by thelfer** [comment]
The relevant part of the error message is `no match for operator '+'`. Apparently, you try to a scalar and a real number. Please check what's wrong at line 245.

**Comment by thelfer** [comment]
Don't know. You have to look in the documention of OpenGeoSys,  I think

**Comment by cbsilver** [comment]
Dear Pavan, dear Thomas,

I am sorry for the late reply. I had some longer vacation.
I had already finished a non-linear version of the Cam clay model, which is working fine. At the moment there is a merge request in order to include it in the OpenGeoSys master branch. So Pavan, you don't need to code this again. It will soon be available.

Best regards,
Christian

**Comment by pavanbhukya** [comment]
Dear @cbsilver 

Thanks for integrating non-linear elasticity into the MCC model. 

May I ask how long it will take for the update in OGS?

If it takes over a month, can you please share the .mfront file with me? I will compile and build it myself.

Thanks
Pavan.

**Comment by pavanbhukya** [comment]
Dear @thelfer,

I need the derivative given below for getting the deviatoric plastic strain

`d/dn_ij [n_ij- ((1/3)*n_ij*delta_ij)]` 

This basically boils down to [2/3 1 1;1 2/3 1;1 1 2/3].

How can I get this tensor? Because the deviatoric projection tensor only has diagonal elements and off-diagonal elements are zero.

Thanks
Pavan.

**Comment by thelfer** [comment]
`Stensor4::Id()-Stensor4::IxI()/3` which is also `Stensor4::K()`

**Comment by pavanbhukya** [comment]
Dear @thelfer 

I have tried that. But, I realised that It's a fourth-order tensor. 

But the required tensor for my case is of second order.

Is there any other way to create this?

**Comment by thelfer** [comment]
You can do something like this:

```
Stensor4::Id()*Stensor::Id()-Stensor::Id()/3
````

**Comment by cbsilver** [comment]
Dear Pavan, dear Thomas,

the update in OGS for the nonlinear Cam clay model won't take longer than two weeks (at maximum). I am right about it.
I'll keep you informed.

Best,
Christian

**Comment by pavanbhukya** [comment]
Dear @cbsilver,

Thanks, I will wait for the update. 

Currently, I am testing a modified form of MCC through the MTest Python API. I have carried out the test for the triaxial drained test. However, I must know how to apply a different stress paths (undrained, constant p' and radial extension etc..).

Do you have any thoughts?

**Comment by pavanbhukya** [comment]
Dear @cbsilver 

Any update on the nonlinear bulk modulus in MCC?
