### ISSUE TITLE
Reg. usage of python file for MTest

### ISSUE THREAD

**Issue by pavanbhukya** [thelfer/tfel#395]
Dear Thomas,

I am using the Python script file for testing the MFront file.

However, I am getting the following errors.

1. `ModuleNotFoundError: No module named 'std'` (I tried installing std module through pip, but couldn't succeed)
2. `ExternalLibraryManager::loadLibrary: library 'src/libBehaviour.so' could not be loaded` (How to give a proper path?)

Please let me know how to resolve these issues.

Thanks
Pavan.

**Comment by thelfer** [comment]
Hi @pavanbhukya
Did you compile the python bindings (i.e. add `-Denable-python-bindings=ON` when calling `cmake`) ?
If so, did you update your `PYTHONPATH`

**Comment by pavanbhukya** [comment]
Dear @thelfer 

I followed the same and exported the paths (see the picture attached).

Even after installing MFront successfully, I couldn't call the mfront/ mtest commands.

![image](https://github.com/thelfer/tfel/assets/105070006/d75f3a1a-5528-47bb-add0-7eda970e809a)

Let me know the issue.

Thanks
Pavan.

**Comment by thelfer** [comment]
I don't understand why you install things in `/usr/local` and set the PATH to `~.local/bin` (which is not a valid path in `bash` BTW)

**Comment by pavanbhukya** [comment]
I am sorry @thelfer 

I just followed the commands from the [webpage](https://tfel.sourceforge.net/install.html).

![image](https://github.com/thelfer/tfel/assets/105070006/11620d1c-0d73-43b4-a45a-c844a72fe806)

**Comment by thelfer** [comment]
Ok, the first line is then wrong. I will correct it. But in this example, we assume that the code is installed in `~/.local/bin`, but you installed `TFEL` in `/usr/local`. You have to adapt those lines to reflect that.

**Comment by pavanbhukya** [comment]
Dear Thomas,

I am getting the following error while running MTest using Python script.

![image](https://github.com/thelfer/tfel/assets/105070006/63ba2d27-dc30-4ce9-a060-14f929418fdf)

Let me know the issue.

Thanks
Pavan.

**Comment by thelfer** [comment]
The error is pretty clear: the library `libBehaviour.so` is not present in the `src` directory.
This may mean that you compiled your behaviour `MFrontCamCaly_semiExplParaInit` in another directory... or that you forgot to compile the behaviour !

**Comment by pavanbhukya** [comment]
Dear @thelfer,

As I failed several times while building MFront through Cmake and giving proper paths, I installed MFront using `spack` package.

But, will it have any downsides (i.e., installation without Python buildings and proper directories to call)?

Because it isn't supporting MTest with python.

Thanks
Pavan.

**Comment by thelfer** [comment]
@pavanbhukya The `spack` package does support python bindings. I have tested it when I made the package. No trouble. See `spack info tfel` for details

**Comment by pavanbhukya** [comment]
Dear @thelfer,

I could see the Python bindings activated in the spack package. However, as I stated earlier, I am getting the same error when I run the command `python3 ModCamClay_TriaxTest.py`.

> Dear Thomas,
> 
> I am getting the following error while running MTest using Python script.
> 
> ![image](https://user-images.githubusercontent.com/105070006/238121633-63ba2d27-dc30-4ce9-a060-14f929418fdf.png)
> 
> Let me know the issue.
> 
> Thanks Pavan.

Does this mean in the spack package, there is no src folder under which `libBehaviour.so` isn't available ? (I checked for src, and there is no such folder in spack package).

I apologise for asking many questions about installation, but I am helpless. Without this, my work is halted. 

Please help me in this regard.

Thanks
Pavan.

**Comment by pavanbhukya** [comment]
Dear @thelfer 

I got the following error after compiling using `mfront --obuild --interface=generic ModCamClay_semiExplParaInit.mfront`

![image](https://github.com/thelfer/tfel/assets/105070006/a0b0f346-6078-49aa-97fb-4bdb686a3fb4)

**Comment by thelfer** [comment]
You shall set the `spack` environement, i.e. `source share/spack/setup-env.sh`

**Comment by pavanbhukya** [comment]
Dear @thelfer,

I am encountered with the following error when I run the mtest using the python script.

![image](https://github.com/thelfer/tfel/assets/105070006/49059e03-d993-445c-bec4-994814174258)

The error occurred at this line.

`m.setImposedStress("SRR", {0: 0, 0.02: -p_con, 1.0: -p_con})`

 what does this mean?

**Comment by thelfer** [comment]
Have you imported the `std` module from `TFEL` ?

**Comment by pavanbhukya** [comment]
Dear @thelfer 

I imported `std` module. It got sorted out. But, now, the error occurred at another line.

![image](https://github.com/thelfer/tfel/assets/105070006/e71a8a2f-83b8-4ed8-a1c9-6302c6f4653e)

I am attaching the code for the same. Let me know the problem.

[ModCamClay_TriaxTest.zip](https://github.com/thelfer/tfel/files/11484020/ModCamClay_TriaxTest.zip)

**Comment by thelfer** [comment]
Not this week. We have a 5 days break in France. Contact me next week !

**Comment by pavanbhukya** [comment]
Dear Dr. Helfer,

I hope you are back in the office. Please help me solve this issue.

Thanks
Pavan

> Dear @thelfer
> 
> I imported `std` module. It got sorted out. But, now, the error occurred at another line.
> 
> ![image](https://user-images.githubusercontent.com/105070006/238534207-e71a8a2f-83b8-4ed8-a1c9-6302c6f4653e.png)
> 
> I am attaching the code for the same. Let me know the problem.
> 
> [ModCamClay_TriaxTest.zip](https://github.com/thelfer/tfel/files/11484020/ModCamClay_TriaxTest.zip)

**Comment by thelfer** [comment]
Normally this issue is solved by importing the `tfel.math` module.

**Comment by pavanbhukya** [comment]
Dear @thelfer 

Thank you very much. It worked, finally.

**Comment by pavanbhukya** [comment]
Dear @thelfer 

I got the following error while building the .mfront file. What does this mean?

![image](https://github.com/thelfer/tfel/assets/105070006/444536cf-8327-458d-8e78-8cdfe3832996)

Thanks
Pavan.

**Comment by thelfer** [comment]
I means that you used spack to compile `mfront`. If you do, `mfront` will use the spack wrapper as the default C++ compiler. You have two choices:

- have a consistent environment and load the gcc that you used to compile `mfront`
- define the `CXX` variable environment which shall point to the compiler that you want to use
  `CXX=/usr/bin/c++ mfront --obuild ....`

**Comment by thelfer** [comment]
@pavanbhukya Shall we close the issue ?

**Comment by pavanbhukya** [comment]
Sure Dr. Helfer. Thank you very much for your help.

**Comment by thelfer** [comment]
Do not hesitate to open new issues or discussions !
