### ISSUE TITLE
ModuleNotFoundError: No module named ‘mgis’ in WSL based Ubuntu 22.04

### ISSUE THREAD

**Issue by ratansahu05** [thelfer/tfel#399]
I want to use mgis.fenics python module and I have tried to build it from source using this [website](https://github.com/thelfer/MFrontGenericInterfaceSupport) and also used `git clone https://github.com/thelfer/tfel` as mentioned in [here](https://fenicsproject.discourse.group/t/problem-about-installing-mgis-fenics-python-module/3197) and compiled it using the instructions given on tfel installation site. I want to download mgis.fenics in WSL Ubuntu 22.04.

Procedure I tried :-
1. I downloaded the zip folder from [here](https://github.com/thelfer/MFrontGenericInterfaceSupport)
2. I extracted MFrontGenericInterfaceSupport-master into my C drive
3. mounted this folder in ubuntu using cd /mnt/c/MFrontGenericInterfaceSupport-master
4. type `cmake .` 
5. type `cmake`
6. type `cmake -Denable-python-bindings=ON`
7. type `cmake -Denable-fenics-bindings=ON`
8. type `cmake -DPython_ADDITIONAL_VERSIONS=3.10`
9. type `make`
10. type `make check`
11. type `sudo make install`
12. type `git clone https://github.com/thelfer/tfel` and compiled using `cmake .`  then `make` then `make check` then 
`sudo make install`
I tried using this [forum](https://fenicsproject.discourse.group/t/problem-about-installing-mgis-fenics-python-module/3197) on fenicsproject forum but unfortunately I am unable to solve the issue.
Error:
`berserker@LAPTOP-S35CGO60:~$ python3
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mgis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'mgis'
>>>
`
After many attempts I am lost, and cannot figure out in which step I have made mistake. Any guidance would be appreciated. 
Thank You

**Comment by ratansahu05** [comment]
> Hello,
> 
> You also have to download the MGIS code and install **mgis** python module. https://github.com/thelfer/MFrontGenericInterfaceSupport
> 
> Works for me with fenics 2019 and Ubuntu 22.04 (EDIT : and I'm using WSL), I installed fenics using conda rather than Ubuntu (better control of python modules I imagine though not certain).
> 
> François.

Hi @fpguillet, thanks for the reply, I don't use fenics via conda rather than that I directly use python and use jupyter notebook as UI to run the code, can you please tell me what steps you followed when you are saying to download the MGIS code and install mgis python module, because I did download the MFrontInterfaceGenericSupport zip and then extracted it and then type `cmake .` then `make` then `make check` then `sudo make install` but that didn't work therefore kindly guide me on how to do this correctly.

Thank You

**Comment by thelfer** [comment]
Hi @ratansahu05,

`sudo make install` shall have installed the python modules in `/usr/local/lib/python3.10/site-packages/` . Would you check if this directory is listed in `PYTHONPATH`  ?

(But you shall first check that `_mgis.so` is in  `/usr/local/lib/python3.10/site-packages/mgis`

**Comment by ratansahu05** [comment]
Hi @thelfer, thanks for the reply, I wanted to install mgis from the source again so I installed it in C: drive and then changed directory to MFrontInterfaceGenericSupport-master (which I extracted the zip file ) but the below error comes:
![image](https://github.com/thelfer/tfel/assets/109655986/1398d0d2-cdf1-4c1d-b910-77c703b80af0)

**Comment by ratansahu05** [comment]
> Hi @ratansahu05,
> 
> `sudo make install` shall have installed the python modules in `/usr/local/lib/python3.10/site-packages/` . Would you check if this directory is listed in `PYTHONPATH` ?
> 
> (But you shall first check that `_mgis.so` is in `/usr/local/lib/python3.10/site-packages/mgis`

Hi @thelfer, thanks for the reply, `_mgis.so` in not present in `/usr/local/lib/python3.10/site-packages/mgis` (kindly see the image attached below)
![image](https://github.com/thelfer/tfel/assets/109655986/5a763a13-784e-437d-877a-87e788dea495)

And I also checked that if `/usr/local/lib/python3.10/site-packages/` directory is listed in `PYTHONPATH` it is not and instead, 3.8 version is showing up but my python version is 3.10 (kindly see the image below)
![image](https://github.com/thelfer/tfel/assets/109655986/8ef6dd42-c475-425b-abac-8df2b2607a8d)

Kindly guide me on what steps should I take from here.
Thank you for the help.

**Comment by fpguillet** [comment]
@ratansahu05, sorry I read pour post too quickly and assumed you installed only TFEL.

Here is the content of my `${MGISHOME}/lib/python3.10/site-packages/` directory :
 `ls ${MGISHOME}/lib/python3.10/site-packages/mgis
__init__.py  __pycache__  _mgis.so  behaviour.so  fenics  material_property.so  model.so`

**Comment by thelfer** [comment]
@ratansahu05 I would think that `-Denable-python-bindings=ON` was not taken into account. Can you use @fpguillet' command (after modifying the install path) and start again ?

**Comment by ratansahu05** [comment]
> @ratansahu05 I would think that `-Denable-python-bindings=ON` was not taken into account. Can you use @fpguillet' command (after modifying the install path) and start again ?

@thelfer yes, I didn't use `cmake -Denable-python-bindings=ON` in the installation process.
Sure i will use @fpguillet command but how do I modify the install path ? I am not able to understand how to do that ? Kindly provide some clarification. Thank You

**Comment by ratansahu05** [comment]
> @ratansahu05, sorry I read pour post too quickly and assumed you installed only TFEL.
> 
> Here is the content of my `${MGISHOME}/lib/python3.10/site-packages/` directory : `ls ${MGISHOME}/lib/python3.10/site-packages/mgis __init__.py __pycache__ _mgis.so behaviour.so fenics material_property.so model.so`
> 
> And here is the command I used to compile MGIS : `cmake ../MFrontGenericInterfaceSupport-master/ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/guilletf/programmes/mgis-08042023 -Denable-c-bindings=ON -Denable-fortran-bindings=OFF -Denable-python-bindings=ON -Denable-website=ON -DPython_ADDITIONAL_VERSIONS=3.10`

@fpguillet sorry but I am not able to locate `MGISHOME` Can you please tell me how to do that ? Thank You.

**Comment by thelfer** [comment]
> @fpguillet sorry but I am not able to locate `MGISHOME` Can you please tell me how to do that ? Thank You.

MGISHOME is just a variable to the installation directory of mgis. In your case, you can replace it by /usr/local.

**Comment by ratansahu05** [comment]
> @ratansahu05, sorry I read pour post too quickly and assumed you installed only TFEL.
> 
> Here is the content of my `${MGISHOME}/lib/python3.10/site-packages/` directory : `ls ${MGISHOME}/lib/python3.10/site-packages/mgis __init__.py __pycache__ _mgis.so behaviour.so fenics material_property.so model.so`
> 
> And here is the command I used to compile MGIS : `cmake ../MFrontGenericInterfaceSupport-master/ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/guilletf/programmes/mgis-08042023 -Denable-c-bindings=ON -Denable-fortran-bindings=OFF -Denable-python-bindings=ON -Denable-website=ON -DPython_ADDITIONAL_VERSIONS=3.10`

@fpguillet @thelfer I have followed the above command and then when I am checking content of my `${MGISHOME}/lib/python3.10/site-packages/ directory` it is showing as (kindly see the image below):
![image](https://github.com/thelfer/tfel/assets/109655986/07d4807a-c2fc-4206-90b9-7ba0d0876754)

`mfm_test_generator  mfront  mgis  mtest  std  tfel` whereas in your case it is different.

**Comment by thelfer** [comment]
Here you seem to have install TFEL's python bindings.
Did recompile MGIS with the python bindings ?

**Comment by ratansahu05** [comment]
> Here you seem to have install TFEL's python bindings. Did recompile MGIS with the python bindings ?

I did the whole process again:
1. cd to` MFrontGenericInterfaceSupport-master` directory
2. `cmake .`
3. `cmake ../MFrontGenericInterfaceSupport-master/ -DCMAKE_BUILD_TYPE=Release -4. DCMAKE_INSTALL_PREFIX=/home/guilletf/programmes/mgis-08042023  -Denable-c-bindings=ON -Denable-fortran-bindings=OFF -Denable-python-bindings=ON -Denable-website=ON -DPython_ADDITIONAL_VERSIONS=3.10`
5. `make`
6. `make check`
7. `sudo make install`
Then I checked the contents of `${MGISHOME}/lib/python3.10/site-packages/ directory`:
`mfm_test_generator  mfront  mgis  mtest  std  tfel`

**Comment by thelfer** [comment]
If you typed `-DCMAKE_INSTALL_PREFIX=/home/guilletf/programmes/mgis-08042023` then mgis is installed in `/home/guilletf/programmes/mgis-08042023`, not in `/usr/local`.

Furthermore, you did not enable the python bindings, i.e. `-Denable-python-bindings=ON` is missing

**Comment by ratansahu05** [comment]
> If you typed `-DCMAKE_INSTALL_PREFIX=/home/guilletf/programmes/mgis-08042023` then mgis is installed in `/home/guilletf/programmes/mgis-08042023`, not in `/usr/local`.
> 
> Furthermore, you did not enable the python bindings, i.e. `-Denable-python-bindings=ON` is missing

@thelfer Thanks for pointing that out, yes mgis is installed in `/home/guilletf/programmes/mgis-08042023` and I also enable the python bindings using `cmake -Denable-python-bindings=ON` (before that cd to `MFrontGenericInterfaceSupport-master` directory ), now what's the next step if I may ask ?
![image](https://github.com/thelfer/tfel/assets/109655986/c1a4459d-d47d-43cc-a6c2-a64fd4258a63)

**Comment by thelfer** [comment]
Update your `PYTHONPATH` to include `/home/guilletf/programmes/mgis-08042023/lib/....` and thats it's: `import mgis` shall work

**Comment by ratansahu05** [comment]
> Update your `PYTHONPATH` to include `/home/guilletf/programmes/mgis-08042023/lib/....` and thats it's: `import mgis` shall work

@thelfer I have included the path but still it shows the same error: (kindly see the image below)
![image](https://github.com/thelfer/tfel/assets/109655986/ac40d768-d13f-4946-8bf3-f9b55d088465)

**Comment by thelfer** [comment]
You must stop the PYTHONPATH at `site-packages` (i.e. remove mgis)

**Comment by ratansahu05** [comment]
> You must stop the PYTHONPATH at `site-packages` (i.e. remove mgis)

Yes, now it is working without error, Thank You So Much @thelfer for solving this issue of mine, I really appreciate your guidance, @fpguillet Thank you also for providing me the code to compile the mgis. Thanks both for your time and patience.

Just a quick quesiton @thelfer is there more documentation available similar to [this](https://thelfer.github.io/mgis/web/mgis_fenics_phase_field.html) because lately I am interested in damage model, but I am only able to find brittle damage models using phase field approach, I also wanted to look and implement some ductile damage models. Therefore if you have any resources regarding this, that'll be great for me.

Thank You for the help.

**Comment by thelfer** [comment]
I currently don't have any tutorial on ductile failure. I will have to work on it for a summer school: https://mealor2.sciencesconf.org/
Don't hesitate to detail the model you plan to use, maybe we can help.

**Comment by JoepStorm** [comment]
I hope it is okay for me to comment here. Following all the steps laid out here does not fully fix the problem for me.

I don't get the "No module named 'mgis'" error anymore, but this error instead:

>>> ~/Programs/mgis/MFrontGenericInterfaceSupport-master$ python3
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
import mgis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/mgis/__init__.py", line 1, in <module>
    from ._mgis import *
ImportError: libMFrontGenericInterface.so: cannot open shared object file: No such file or directory

Do any of you know what I did wrong?

**Comment by thelfer** [comment]
@JoepStorm looks like the  `libMFrontGenericInterface.so` is not listed in `LD_LIBRARY_PATH`, but that's strange since you seem to have installed `mgis` in `/usr/local/lib` which should not  require to update `LD_LIBRARY_PATH`. Does   `/usr/local/lib`  contain `libMFrontGenericInterface.so` ?

**Comment by JoepStorm** [comment]
Thank you for the response. Yes, it does contain the file. Here is a screenshot of the contents of my `/usr/local/lib`:
![image](https://github.com/thelfer/tfel/assets/39797353/3524e90b-837b-4cf1-8588-06f325be37d7)

In case its relevant, I've appended my `.bashrc` with `export PYTHONPATH=/usr/local/lib/python3.10/site-packages/`.

**Comment by thelfer** [comment]
Would you try again after updating `LD_LIBRARY_PATH` with `export LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH`

**Comment by JoepStorm** [comment]
That fixed it, thank you! I had set the path to a different path, namely `export LD_LIBRARY_PATH=$MPIROOT/lib:$LD_LIBRARY_PATH`  for a different library.

**Comment by JoepStorm** [comment]
I would like to ask for more help. I want to use a conda environment instead of my system default, but I am unable to get CMake to find Boost.
To test it, I've created a simple conda environment with various boost dependencies:
```
name: py_boost
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.7
  - numpy
  - boost
  - boost-cpp
  - libboost
  - libboost-devel
  - libboost-headers
  - libboost-python
  - libboost-python-devel
```
When calling CMake (from inside this conda environment), I get the following error:
```
$ cmake ../MFrontGenericInterfaceSupport-master/ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local/ -Denable-c-bindings=ON -Denable-fortran-bindings=OFF -Denable-python-bindings=ON -Denable-website=ON -DPython_ADDITIONAL_VERSIONS=3.11 -DPYTHON_EXECUTABLE=/home/joep/anaconda3/envs/py_boost/bin/python -DPYTHON_LIBRARY=/home/joep/anaconda3/envs/py_boost/lib/libpython3.11.so -DPYTHON_INCLUDE_DIR=/home/joep/anaconda3/envs/py_boost/include/python3.11
-- Found PythonLibs: /home/joep/anaconda3/envs/py_boost/lib/libpython3.11.so (found version "3.11.7") 
-- found python          3.11.7
-- python include path   /home/joep/anaconda3/envs/py_boost/include/python3.11
-- python libraries path /home/joep/anaconda3/envs/py_boost/lib
-- python library        python3.11
-- Found PythonInterp: /home/joep/anaconda3/envs/py_boost/bin/python (found suitable version "3.11.7", minimum required is "3.11.7") 
-- python interpreter    /home/joep/anaconda3/envs/py_boost/bin/python
-- Trying to find libboost_python-py311
-- Could NOT find Boost: missing: python-py311 (found /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found suitable version "1.74.0", minimum required is "1.36.0"))
-- Trying to find libboost_python311
-- Could NOT find Boost: missing: python311 (found /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found suitable version "1.74.0", minimum required is "1.36.0"))
-- Trying to find libboost_python-py3
-- Could NOT find Boost: missing: python-py3 (found /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found suitable version "1.74.0", minimum required is "1.36.0"))
-- Trying to find libboost_python3
-- Could NOT find Boost: missing: python3 (found /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found suitable version "1.74.0", minimum required is "1.36.0"))
-- Trying to find libboost_python
-- Could NOT find Boost: missing: python (found /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found suitable version "1.74.0", minimum required is "1.36.0"))
CMake Error at CMakeLists.txt:116 (message):
  Boost python libraries not found.
...
```
What am I doing wrong?

**Comment by thelfer** [comment]
Seems working with `miniconda3`:

~~~~
$ python
Python 3.12.1 | packaged by Anaconda, Inc. | (main, Jan 19 2024, 15:51:05) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mfront
>>> 
~~~~

I did not try mgis yet, but I am confident. Here is my cmake call:

~~~~
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/tmp/install ~/codes/tfel/master/src/tfel/ -Denable-python-bindings=ON -DUSE_EXTERNAL_COMPILER_FLAGS=ON  -DPython_ADDITIONAL_VERSIONS=3.12  -DPYTHON_LIBRARY=/home/th202608/codes/miniconda3/lib/libpython3.so -DPYTHON_INCLUDE_DIR=/home/th202608/codes/miniconda3/include/python3.12/
~~~~

I needed to install those packages:

~~~~
conda install gcc_linux-64  gxx_linux-64 numpy py-boost
~~~~
