### ISSUE TITLE
[CMake]: Exporting TFEL build tree for use by external projects

### ISSUE THREAD

**Issue by pbouda95** [thelfer/tfel#4]
Hello Thomas,

Until now, (version 3.4.0-dev), tfel integration in FE codes might be tricky notably when its build/install separately. Indeed, internal links/dependencies between tfel files (e.g. between shared libraries) has to be mentioned explicitly in the main cmake project. 

This issue may be solved by a new paradigm introduced with modern CMake (3.1+) owing to the EXPORT attribute in INSTALL function.
 
Alas, tfel does not embed this option. Is it possible to do something about this ?

Cheers,
Pascal Bouda

**Comment by thelfer** [comment]
Hi Pascal,
I created the following ticket on sourceforge: https://sourceforge.net/p/tfel/tickets/206/
Thomas

**Comment by thelfer** [comment]
The issue should have been fixed with the release of Version 3.4
