### ISSUE TITLE
LibrariesManager::extract: could not load symbol 'Ducan_chang_BehaviourType'

### ISSUE THREAD

**Issue by LearnmanV** [thelfer/tfel#400]
I used Mfront to develop the Duncan Chang constitutive model in code_ Aster；The Mfront file for this constitution has been compiled, but this error occurred during  calculation using SIMU_POINT_MAT.

**Comment by thelfer** [comment]
@LearnmanV `code_aster` recently made a big move toward the `generic` interface (support for the native interface, named `aster` , has been removed) .
So the first question is how did you compile your behaviour ?

**Comment by LearnmanV** [comment]
> @LearnmanV `code_aster` recently made a big move toward the `generic` interface (support for the native interface, named `aster` , has been removed) . So the first question is how did you compile your behaviour ?

https://gitlab.com/codeaster-opensource-documentation/opensource-installation-development/-/blob/main/devel/compile.md
sir,you can see this ,https://gitlab.com/codeaster-opensource-documentation/opensource-installation-development/-/blob/main/devel/compile.md#working-within-the-container

**Comment by LearnmanV** [comment]
@thelfer
https://github.com/thelfer)https://gitlab.com/codeaster-opensource-documentation/opensource-installation-development/-/blob/main/devel/compile.md
sir,you can see this ,https://gitlab.com/codeaster-opensource-documentation/opensource-installation-development/-/blob/main/devel/compile.md#working-within-the-container

**Comment by LearnmanV** [comment]
@thelfer
I can run export ,comm,mfront documents  in the shell environmental of salome_meca,to complie my behaviour.

**Comment by thelfer** [comment]
@LearnmanV That does not tell me how your MFront file is compile. Did you use `MFRONT_CREA_LIB` in you `.comm` file ?

**Comment by thelfer** [comment]
@LearnmanV Shall we close the issue ?
