### ISSUE TITLE
RuntimeError: LibrariesManager::loadLibrary: library './src/libBehaviour.so' could not be loaded, (./src/libBehaviour.so: cannot open shared object file: No such file or directory)

### ISSUE THREAD

**Issue by ratansahu05** [thelfer/tfel#401]
Hello, I tried to implement [this](https://thelfer.github.io/mgis/web/mgis_fenics_phase_field.html#mfront-behaviour-for-the-damage-problem) tutorial on phase field approach to brittle fracture but when I am running this part of code :
```
E, nu = 200, 0.2
material_u = mf.MFrontNonlinearMaterial("./src/libBehaviour.so",
                                      "PhaseFieldDisplacementDeviatoricSplit",
                                      hypothesis="plane_strain",
                                      material_properties={"YoungModulus": E,
                                                            "PoissonRatio": nu})
problem_u = mf.MFrontNonlinearProblem(u, material_u, quadrature_degree=0, bcs=bcu)
problem_u.register_external_state_variable("Damage", d)
H = problem_u.get_state_variable("HistoryFunction")
problem_u.solver.parameters["report"] = False
```
I am getting following error:
```
RuntimeError                              Traceback (most recent call last)
/home/guilletf/programmes/mgis-08042023/lib/python3.10/site-packages/mgis/fenics/nonlinear_material.py in __init__(self, path, name, hypothesis, material_properties, parameters, rotation_matrix)
     65         try:
---> 66             self.load_behaviour()
     67         except:

/home/guilletf/programmes/mgis-08042023/lib/python3.10/site-packages/mgis/fenics/nonlinear_material.py in load_behaviour(self)
     83     def load_behaviour(self):
---> 84         self.is_finite_strain = mgis_bv.isStandardFiniteStrainBehaviour(
     85             self.path, self.name)

RuntimeError: LibrariesManager::loadLibrary: library './src/libBehaviour.so' could not be loaded, (./src/libBehaviour.so: cannot open shared object file: No such file or directory)

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_9925/2009296422.py in <module>
      1 E, nu = 200, 0.2
----> 2 material_u = mf.MFrontNonlinearMaterial("./src/libBehaviour.so",
      3                                       "PhaseFieldDisplacementDeviatoricSplit",
      4                                       hypothesis="plane_strain",
      5                                       material_properties={"YoungModulus": E,

/home/guilletf/programmes/mgis-08042023/lib/python3.10/site-packages/mgis/fenics/nonlinear_material.py in __init__(self, path, name, hypothesis, material_properties, parameters, rotation_matrix)
     78             ])
     79             os.chdir(cwd)
---> 80             self.load_behaviour()
     81         self.update_parameters(parameters)
     82 

/home/guilletf/programmes/mgis-08042023/lib/python3.10/site-packages/mgis/fenics/nonlinear_material.py in load_behaviour(self)
     82 
     83     def load_behaviour(self):
---> 84         self.is_finite_strain = mgis_bv.isStandardFiniteStrainBehaviour(
     85             self.path, self.name)
     86         if self.is_finite_strain:

RuntimeError: LibrariesManager::loadLibrary: library './src/libBehaviour.so' could not be loaded, (./src/libBehaviour.so: cannot open shared object file: No such file or directory)
```
I also checked if `libBehaviour.so` is present in `src` or not so, it was not present that is why error is coming, therefore I humbly request to tell me how to deal with this error.
Thank you

**Comment by thelfer** [comment]
You have to understand how MFront works. MFront generates shared libraries that can be plugged in various solvers.

mgis.fenics thus uses shared libraries generated by MFront.

This means that you have to compile the shared libraries before running your simulation.

Let us assume that you have the `PhaseFieldDisplacementDeviatoricSplit.mfront` in your current directory, the proper way to generate a shared library usable in mgis.fenics is:

```bash
$ mfront --obuild --interface=generic PhaseFieldDisplacementDeviatoricSplit.mfront
```

By default, the name of the shared library is `libBehaviour.so` and if the previous compilation process succeeded, will be placed in the `src` subdirectory (hence the path used in the tutorial).

Note that the implementations and scripts can be downloaded here: https://gitlab.enpc.fr/navier-fenics/mgis-fenics-demos/-/tree/master/demos/phase_field

**Comment by ratansahu05** [comment]
> You have to understand how MFront works. MFront generates shared libraries that can be plugged in various solvers.
> 
> mgis.fenics thus uses shared libraries generated by MFront.
> 
> This means that you have to compile the shared libraries **before** running your simulation.
> 
> Let us assume that you have the `PhaseFieldDisplacementDeviatoricSplit.mfront` in your current directory, the proper way to generate a shared library usable in mgis.fenics is:
> 
> ```shell
> $ mfront --obuild --interface=generic PhaseFieldDisplacementDeviatoricSplit.mfront
> ```
> 
> By default, the name of the shared library is `libBehaviour.so` and if the previous compilation process succeeded, will be placed in the `src` subdirectory (hence the path used in the tutorial).
> 
> Note that the implementations and scripts can be downloaded here: https://gitlab.enpc.fr/navier-fenics/mgis-fenics-demos/-/tree/master/demos/phase_field

Thanks @thelfer for explaining the workflow of MFront and mgis.fenics, the code is working fine now. Thank You for your time.
