### ISSUE TITLE
Problem with deviator when compiling with Sycl

### ISSUE THREAD

**Issue by Salemkll** [thelfer/tfel#402]
I have a problem while compiling with Sycl (more precisely with `HIPSYCL_TARGETS='cuda-nvcxx'`)when I use the  function `deviator` from TFEL in my GPU kernel. I get the following error during compilation:`NVC++-F-0155-Compiler failed to translate accelerator region (see -Minfo messages): Unsupported procedure (/path/mycode.cxx: 1)`. When I rewrote deviator in my kernel, I noticed that I encountered the same error with `EvaluationResult` from `deviator` ( `EvaluationResult` is probably the source of the problem)

**Comment by thelfer** [comment]
Thanks for reporting !

**Comment by thelfer** [comment]
The trouble seems to be related to the initialization of a symmetric tensor from an `std::initializer_list`. This version of `deviator` just works:

```cxx
template <typename StensorType>
constexpr std::enable_if_t<implementsStensorConcept<StensorType>(),
                           EvaluationResult<StensorType>>
my_deviator(const StensorType& s) {
  using Result = EvaluationResult<StensorType>;
  using real = base_type<numeric_type<StensorType>>;
  constexpr auto N = getSpaceDimension<StensorType>();
  static_assert((N == 1) || (N == 2) || (N == 3), "invalid space dimension");
  constexpr const auto one_third = real{1} / real{3};
  const auto tr = one_third * trace(s);
  if constexpr (N == 1u) {
    Result r;
    r(0) = s(0) - tr;
    r(1) = s(1) - tr;
    r(2) = s(2) - tr;
    return r;
  } else if constexpr (N == 2u) {
    Result r;
    r(0) = s(0) - tr;
    r(1) = s(1) - tr;
    r(2) = s(2) - tr;
    r(3) = s(3);
    return r;
  } else if constexpr (N == 3u) {
    Result r;
    r(0) = s(0) - tr;
    r(1) = s(1) - tr;
    r(2) = s(2) - tr;
    r(3) = s(3);
    r(4) = s(4);
    r(5) = s(5);
    return r;
  }
}  // end of deviator
```

**Comment by thelfer** [comment]
I confirm that the issue is also present with the latest version of nvcc

**Comment by thelfer** [comment]
@Salemkll Thanks for you tests !
