### ISSUE TITLE
Problem with saving individual contributions to the porosity evolutions in dedicated auxiliary state variables 

### ISSUE THREAD

**Issue by hureje** [thelfer/tfel#409]
The save_porosity_increase option in the StandardElastoViscoPlasticity brick is not working (compilation error with the file below)

@DSL Implicit;
@Behaviour GTN;

@UMATUseTimeSubStepping true;
@UMATMaximumSubStepping 100;

@ModellingHypotheses{".+"};
//@StrainMeasure Hencky;

@Algorithm NewtonRaphson;
@Epsilon 1.e-12;
@Theta 1;

@MaterialProperty real xyoung;
@MaterialProperty real xnu;
@MaterialProperty real xR0;
@MaterialProperty real xRinf;
@MaterialProperty real xb;
@MaterialProperty real xq1;
@MaterialProperty real xq2;
@MaterialProperty real xq3;
@MaterialProperty real xfc;
@MaterialProperty real xfr;
@MaterialProperty real xfn;
@MaterialProperty real xen;
@MaterialProperty real xsn;

@MaterialProperty real xR02;
@MaterialProperty real xRinf2;
@MaterialProperty real xb2;

@Brick StandardElastoViscoPlasticity{
  stress_potential : "Hooke" {
    young_modulus : "xyoung", 
    poisson_ratio : "xnu"
  },
  inelastic_flow : "Plastic" {
    criterion : "GursonTvergaardNeedleman1982" {
      f_c : "xfc",
      f_r : "xfr",
      q_1 : "xq1",
      q_2 : "xq2",
      q_3 : "xq3"
    },
    isotropic_hardening : "Voce" {
       R0   : "xR0",
       Rinf : "xRinf",
       b    : "xb"
    },
    isotropic_hardening : "Voce" {
       R0   : "xR02",
       Rinf : "xRinf2",
       b    : "xb2"
    },
    save_porosity_increase : true
  },
  porosity_evolution : {
    nucleation_model : "Chu-Needleman 1980 (strain)" {
	fn : "xfn", 
	en : "xen", 
	sn : "xsn"
	}
  }
};

**Comment by thelfer** [comment]
Thanks for reporting @hureje !
