### ISSUE TITLE
How to set orthotropic plastic behaviour in CalculiX

### ISSUE THREAD

**Issue by thodec95** [thelfer/tfel#413]
Hello everyone,

I implemented orthotropic plastic behaviour in CalculiX. But I don‘t know how to set the input data.

I already asked in the CalculiX forum, but got no answer.

The behaviour I used is this one:

[tfel.sourceforge.net/gallery/plasticity/OrthotropicLinearHardeningPlasticity.mfront ](https://tfel.sourceforge.net/gallery/plasticity/OrthotropicLinearHardeningPlasticity.mfront)

Here’s my input data:

**
** GEOMETRY
**
*Node
1, 0., 0., 1.
2, 0., 1., 1.
3, 0., 0., 0.
4, 0., 1., 0.
5, 1., 0., 1.
6, 1., 1., 1.
7, 1., 0., 0.
8, 1., 1., 0.
*Element, type=C3D8, elset=cube
1, 5, 6, 8, 7, 1, 2, 4, 3
*Solid Section, elset=cube, material=@CALCULIXBEHAVIOUR_OrthotropicLinearHardeningPlasticity, ORIENTATION=OR
*Nset, nset=sx2, generate
5, 8, 1
*Nset, nset=sx1, generate
1, 4, 1
*Nset, nset=sy1
1, 3, 5, 7
*Nset, nset=sy2
2, 4, 6, 8,
*Nset, nset=sz1
3, 4, 7, 8
*Nset, nset=sz2
1, 2, 5, 6,
**
** MATERIAL
**
*Material, name=@CALCULIXBEHAVIOUR_OrthotropicLinearHardeningPlasticity
*User Material, constants=17
7.8e+10,2.64233e+11,3.32e+11,
0.13,0.24,0.18,
4.8e+10,1.16418e+11,7.8e+10
0.371,0.629,4.052,1.5,1.5,1.5
150e6
150e9
*Depvar
17
**
*ORIENTATION,NAME=OR
0.,0.,0.,0.,0.,0.
** LOADING
**
*Step, nlgeom=YES
*Static
0.02, 1., 1e-05, 0.2
*Boundary
sx1, 1, 1
*Boundary
sy1, 2,2
*Boundary
sz1, 3,3
*Boundary
sx2, 1, 1, 0.2
*EL PRINT, ELSET=cube
E, S
*EL FILE
S
*NODE FILE
U
*End Step

Has the MFront code to be modified, because there are already values in the code? And is my input data correct? Especially with the depvar I’m very unsure.

CalculiX stops at the first iteration. What could I do?

Decascading the MPC’s

Determining the structure of the matrix:
number of equations
8
number of nonzero lower triangular matrix elements
28

increment 1 attempt 1
increment size= 2.000000e-02
sum of previous increments=0.000000e+00
actual step time=2.000000e-02
actual total time=2.000000e-02

iteration 1

Using up to 1 cpu(s) for the stress calculation.

Using up to 1 cpu(s) for the symmetric stiffness/mass contributions.

Factoring the system of equations using the symmetric spooles solver
Using up to 1 cpu(s) for spooles.

**Comment by thelfer** [comment]
Hi @thodec95,

I never made any computation in orthotropy with `CalCuliX`. If I remember things correctly, orthotropy is handled by `CalculiX`.

One thing seems strange: Why are all your orientation vectors null ? Are you sure that the rotation matrix is not null ?

If that's normal,  would you tell me which version of `CalculiX` you are using ? And by the way which version of `MFront`

**Comment by thodec95** [comment]
Hi @thelfer,

I wanted a local axis system, that is similar to the global one. Without defintion of the *ORIENTATION card CalculiX says there is no orientation defined. Now I changed the orientation to:

*ORIENTATION, NAME=OR,SYSTEM=RECTANGULAR
1.,0.,0.,1.,1.,0.

The result is the same as before. I don't know if the Material constants and the depvar are defined correctly for the OrthotropicLinearHardeningPlasticity behaviour.

I use CalculiX 2.17 and MFront 4.2.0.

**Comment by thelfer** [comment]
@thodec95 Sorry for the late reply. Did you manage to solve your issue ?

**Comment by thodec95** [comment]
I didn't try anymore.

**Comment by thelfer** [comment]
Still worth investigating ?
