### ISSUE TITLE
Failed compilation with GCC- 13.1.1 on tfel 4.10

### ISSUE THREAD

**Issue by baristelmen** [thelfer/tfel#414]
## Failed compilation with GCC- 13.1.1 on tfel 4.10
Failed compiling under arch linux using GCC 13.1.1. Cmake passes correctly but make command fails with error. 

**Tested tfel version - 4.10**

## Environment
** OS: Arch Linux
** CPU architecture: x86_64
** GCC- 13.1.1
** GNU Fortran 13.1.1

## CMake Configuration
`cmake -DCMAKE_BUILD_TYPE=Release -Denable-fortran=ON -Denable-aster=ON -Dlocal-castem-header=OFF -Denable-python-bindings=ON -Denable-python=ON -Denable-abaqus=ON -Denable-testing=ON -Denable-numpy-support=ON -Denable-testing=ON -Denable-mfront-quantity-tests=ON -Denable-diana-fea=ON -Denable-calculix=ON -Denable-ansys=ON -Denable-europlexus=ON -Denable-cyrano=ON -Denable-zmat=OFF -Denable-castem-pleiades=ON -Denable-comsol=ON -Denable-java=OFF -Denable-eigen=OFF -Denable-mkl=OFF -Denable-doxygen-doc=ON -Denable-reference-doc=ON -Denable-website=ON -Denable-reference-doc=ON -Wno-dev ..`
 
## Abstract of errors
/repos/tfel-TFEL-4.1.0/src/System/LibraryInformation-elf_info.cxx:23:10: error: ‘uint16_t’ in namespace ‘std’ does not name a type; did you mean ‘wint_t’?
   23 |     std::uint16_t e_type;      /* Object file type */
      |          ^~~~~~~~
      |          wint_t
/repos/tfel-TFEL-4.1.0/src/System/LibraryInformation-elf_info.cxx:24:10: error: ‘uint16_t’ in namespace ‘std’ does not name a type; did you mean ‘wint_t’?
   24 |     std::uint16_t e_machine;   /* Architecture */
      |          ^~~~~~~~
      |          wint_t
/repos/tfel-TFEL-4.1.0/src/System/LibraryInformation-elf_info.cxx:25:10: error: ‘uint32_t’ in namespace ‘std’ does not name a type; did you mean ‘wint_t’?
   25 |     std::uint32_t e_version;   /* Object file version */
      |          ^~~~~~~~
      |          wint_t
/repos/tfel-TFEL-4.1.0/src/System/LibraryInformation-elf_info.cxx:29:10: error: ‘uint32_t’ in namespace ‘std’ does not name a type; did you mean ‘wint_t’?
   29 |     std::uint32_t e_flags;     /* Processor-specific flags */
      |          ^~~~~~~~
      |          wint_t
/repos/tfel-TFEL-4.1.0/src/System/LibraryInformation-elf_info.cxx:30:10: error: ‘uint16_t’ in namespace ‘std’ does not name a type; did you mean ‘wint_t’?
   30 |     std::uint16_t e_ehsize;    /* ELF header size in bytes */
      |          ^~~~~~~~
      |          wint_t
/repos/tfel-TFEL-4.1.0/src/System/LibraryInformation-elf_info.cxx:31:10: error: ‘uint16_t’ in namespace ‘std’ does not name a type; did you mean ‘wint_t’?
   31 |     std::uint16_t e_phentsize; /* Program header table entry size */
      |          ^~~~~~~~
      |          wint_t
/repos/tfel-TFEL-4.1.0/src/System/LibraryInformation-elf_info.cxx:32:10: error: ‘uint16_t’ in namespace ‘std’ does not name a type; did you mean ‘wint_t’?
   32 |     std::uint16_t e_phnum;     /* Program header table entry count */
      |          ^~~~~~~~
      |          wint_t
/repos/tfel-TFEL-4.1.0/src/System/LibraryInformation-elf_info.cxx:33:10: error: ‘uint16_t’ in namespace ‘std’ does not name a type; did you mean ‘wint_t’?
   33 |     std::uint16_t e_shentsize; /* Section header table entry size */
      |          ^~~~~~~~
      |          wint_t
/repos/tfel-TFEL-4.1.0/src/System/LibraryInformation-elf_info.cxx:34:10: error: ‘uint16_t’ in namespace ‘std’ does not name a type; did you mean ‘wint_t’?
   34 |     std::uint16_t e_shnum;     /* Section header table entry count */
      |          ^~~~~~~~
      |          wint_t
/repos/tfel-TFEL-4.1.0/src/System/LibraryInformation-elf_info.cxx:35:10: error: ‘uint16_t’ in namespace ‘std’ does not name a type; did you mean ‘wint_t’?
   35 |     std::uint16_t e_shstrndx;  /* Section header string table index */
      |          ^~~~~~~~
      |          wint_t

## Affected files
* src/System/LibraryInformation.cxx
* mfront/src/BehaviourProfiler.cxx

## Problem source
GCC stopped including <stdint.h> and <cstdint> on version 13. As such, C++ programs that used standard library components without including the right headers will no longer compile. Therefore, an extra header is required. As per the error above,

* <cstdint> (for std::int8_t, std::int32_t etc.)

Source: **https://gcc.gnu.org/gcc-13/porting_to.html#header-dep-changes**

## Possible workaround
The addition of a header on affected files terminates compilation successfully using GCC 13.1.1
* `#include <cstdint>`

**Warning: The unit tests or behavior law developments are not tested yet.**

**Comment by thelfer** [comment]
@baristelmen Sorry for the late reply, I am struggling to reproduce the bug. `gcc-13.0` works fine

**Comment by thelfer** [comment]
I can't get my hand on a 13.1 version of `gcc` (I get linking errors at the very end of the compilation process).

I added the fix (`#include <cstdint>`) for `src/System/LibraryInformation.cxx`. 

The `mfront/src/BehaviourProfiler.cxx` already includes this file.

**Comment by baristelmen** [comment]
Hello, I guess the compilation of GCC might differ between distros, especially in Arch. Including the header on these two files terminates the compilation successfully and example behavior laws are working expected. 

However, "mfront/src/BehaviourProfiler.cxx" this file in version 4.10 (release) does not include `#include <cstdint>`. Perhaps, a re-release is required for this version?

**Comment by thelfer** [comment]
Juste tested with gcc 13.1.1: the master branch and all rliv branches compile. I did not try with with tfel-4.1.0, but you may have more luck with rliv-4.1 !

**Comment by thelfer** [comment]
@baristelmen Would you tell me if rliv-4.1 is ok for you now ?
Thanks.
Thomas

**Comment by baristelmen** [comment]
Hello @thelfer, I'm sorry, I had a limited internet connection the last few days. I have tested the rliv-4.1 just right now,

- Configuring using Cmake with the configuration listed on #414 works perfectly
- Compilation terminates correctly
- Material behavior ChabocheViscoPlasticity (I'm using this as a base for my work) compiles and testing works 

Thank you very much for the update.
Baris
