### ISSUE TITLE
Accessing elements of Stensor?

### ISSUE THREAD

**Issue by mrgprasad** [thelfer/tfel#420]
Hi Mfront developers,

How do access the elements of an Stensor?? Ex: `const auto Id  = Stensor::Id();` 

A simple `printf("Identity: %lf, %lf, %lf\n", Id[0,0], Id[0,1], Id[0,2]);` gives me: [1, 1, 1]
This is not correct as its an identity tensor

**Comment by thelfer** [comment]
Dear @mrgprasad,

`C++` does not allow multiple indexes in the `[]` operator (prior to C++23 which is not yet supported by `TFEL/MFront`). Your syntax does not do what you meant, sorry for this pitfall of the language.

You must understand that second order tensors are stored as vectors (see <https://thelfer.github.io/tfel/web/tensors.html> and more precisely paragraph 1.2).

Note that the best way to print a tensor is simply:

```cxx
const auto id = Stensor::Id();
std::cout << id << '\n';
```

which shall print `[1,1,1,0,0,0]` in  `3D` according to the rules described in the documentation.

**Comment by thelfer** [comment]
@mrgprasad Could we close the issue ?

**Comment by mrgprasad** [comment]
Yes, thank you
