### ISSUE TITLE
symmetric_product_abc function for Stensors and its derivatives ?

### ISSUE THREAD

**Issue by davidsiedel** [thelfer/tfel#421]
Hi @thelfer,

Regarding tensor operations in `MFront/Math`, I am looking for a function `symmetric_product_abc` (which does the same as `symmetric_product_aba`, but with a third `Stensor` c) and its derivatives. If I am not mistaken, such a function is not implemented yet. Is that so ? If this is the case, I am considering implementing it. As such, would you be interested in a merge request on this topic ?

Thank you very much in advance for your advice,

Best,

David Siedel

**Comment by thelfer** [comment]
Hi @davidsiedel,

That function does not exists yet. Would you tell me in which context you need this ?

Thomas

**Comment by davidsiedel** [comment]
Thanks for your quick reply.

I am currently working on the implementation of a visco-hyperelastic constitutive law using `MFront`, and I need such a function in order to compute the derivative of the prodcut of two symmetric second order tensors A and B (with respect to either A or B). I had in mind that I could use some generic function `symmetric_product_abc` and its derivatives, with c being the identity. Would that be a proper way to proceed ?

**Comment by thelfer** [comment]
First, remember that C = A * B is not symmetric. Thus d(A*B)_dA is an object of the `st2tot2` class.

In TFEL/Math, you already have the methods `st2tot2<N, T>::tpld` (tensor product left derivative) and `st2tot2<N, T>::tpld` (tensor product right derivative).

For instance:

```cxx
const auto dAB_dA = st2tot2<N, real>::tpld(B);
```

**Comment by thelfer** [comment]
@davidsiedel, also note that if you have something like `D = A(C) * B` (A and C being symmetric) and wish to compute `dD_dC`, you can use an optimized version of `tpld`:

```cxx
dD_dC = st2tot2<N,real>::tpld(B, dA_dC);
```

which will be more efficient than using the chain rule:

```cxx
dD_dC = st2tot2<N,real>::tpld(B) * dA_dC;
```
