### ISSUE TITLE
Reg. inclusion of fluid saturation as an input into the MCC framework 

### ISSUE THREAD

**Issue by pavanbhukya** [thelfer/tfel#423]
Dear @thelfer 

I am Pavan. I work with MFront in OpenGeoSys. I am solving a Hydro-Mechanical problem with fluid pressure and deformation as primary variables. I am using a Modified Cam Clay (MCC) based constitutive framework for mechanics. However, I want to include fluid saturation, _S_r_ (which is a secondary variable in the fluid phase mass balance) as an input to expand/contract my MCC yield surface by altering the pre-consolidation pressure. 

![image](https://github.com/thelfer/tfel/assets/105070006/84da5b01-174e-4d66-aa89-04a193653cc1)

Please let me know if there is any way to include this. 

Thanks
Pavan.

**Comment by thelfer** [comment]
Dear @pavanbhukya 
Is your behavour still purely mechanical ? I mean, would you tell me how the suction is handled by the behaviour: as a gradient or as an external state variable ?
Thomas

**Comment by pavanbhukya** [comment]
Dear @thelfer 

I suppose the saturation is an external state variable that controls the size of the yield surface. Whereas, suction is the primary variable of Rechard's fluid flow equation and it is related to saturation by the relative permeability models (e.g., van Genuchten or Brooks-Corey models). 

I am sorry if it is not clear to you yet. I am attaching the link to the relevant paper for your clarification.

[https://doi.org/10.1061/(ASCE)GM.1943-5622.0001845](url)

Let me know if you can't access it.

Thanks
Pavan.

**Comment by thelfer** [comment]
The  relative permeability models are not part of your behaviour, i.e. the saturation is not computed by your mechanical behaviour, right ?
If so, I assume that the saturation is directly passed as an external state variable to the behaviour, i.e. you have directly access in the behaviour at the value of the saturation at the beginning of the time state and the increment of the saturation.
Is that right ?

**Comment by pavanbhukya** [comment]
You are correct. Saturation is not computed by the mechanical models. It is externally supplemented after solving the fluid phase mass balance equation at each time step. So, as you said saturation is an external state variable. 

However, currently, I am not sure how to supplement the saturation values to the mechanical model.

**Comment by thelfer** [comment]
>  I am not sure how to supplement the saturation values to the mechanical model.

You shall define as an external state variable as follows:

~~~~cxx
@ExternalStateVariable real S;
~~~~

This gives you access to two variables:

- S which is the value of the saturation at the beginning of the time step
- S which is the value of the increment of the saturation during the time step

**Comment by pavanbhukya** [comment]
You are correct Dr. @thelfer. I am sure of it.

However, I need to find a way to extract saturations from the fluid phase mass balance equation and coupling it with the MFront in OpenGeoSys. 

I will contact the OGS team and find out if there is anyway. Because there is no benchmark problem on this type of problem in OGS.

Thanks
Pavan.

**Comment by thelfer** [comment]
Pretty sure that @nagelt will help you :)
