### ISSUE TITLE
[mtest] Imposed inner radius evolution in pipe modelling

### ISSUE THREAD

**Issue by fabonimus** [thelfer/tfel#43]
Dear Thomas,
I would like to impose via the module `PTest` the evolution of the inner radius of a pipe.
Is it possible to do this with the module `PTest` in `MTest` ?
Best regards,
Fabien

**Comment by thelfer** [comment]
The following code shows how to impose the evolution of the inner radius of the pipe:

```cxx
@RadialLoading 'ImposedInnerRadius';
@InnerRadiusEvolution{0 : 4.2e-3, 1 : 4.3e-3};
```

**Comment by thelfer** [comment]
@fabonimus The `rliv-3.4` and `master` branches have been updated.
