### ISSUE TITLE
Problème de la génération Mtest avec Amitex

### ISSUE THREAD

**Issue by se263113** [thelfer/tfel#430]
Bonjour, lors de l'utilisation de la commande pour générer des fichiers mtest, il y a un décalage des valeurs des paramètres récupérées d'Amitex ce qui fait que je je ne peux pas analyser les problèmes de convergence lié à ma loi mfront.

**Comment by thelfer** [comment]
Which version are you using ?
Is it related to this issue: https://thelfer.github.io/tfel/web/release-notes-4.1.html#issue-36-mfront-improved-support-for-mtest-file-generation-all-kind-of-state-variables

**Comment by se263113** [comment]
Version of what ? Amitex or Mfront ?

**Comment by se263113** [comment]
I am Salomon EL BEZ. And I don't know my version. I would tell you the same version than the version you use in MFront with the Poretellette Law and your BRICK

**Comment by thelfer** [comment]
The result of `mfront --version`

**Comment by se263113** [comment]
version = castem

**Comment by se263113** [comment]
Version 3.1.2

**Comment by thelfer** [comment]
This version is completely obsolete. Your issue is problably solved in 4.1.

**Comment by se263113** [comment]
And how can I change my version ? With /soft/pleiades/  ?

**Comment by thelfer** [comment]
```bash
$ source /soft/pleiades/codes/PREREQUIS/PREREQUIS-3.6.0/env.sh
```
