### ISSUE TITLE
[tfel:discussion] UserDefinedViscoplasticity and Plastic flows

### ISSUE THREAD

**Issue by thelfer** [thelfer/tfel#432]
Hi Thomas,

I am trying to use the StandardElastoViscoPlasticity brick with 2 inelastic flows.

The first is an instantanous plastic flow with a Voce isotropic hardening and an Armstrong-Frederick kinematic hardening.
The second is a "UserDefinedViscoplasticity" flow.
When the compilation is done with only one inelastic flow (first or second), the library is built.
When I compile with the two types of inelastic flows together, the error is :

In file included from umatEurofer.cxx:15:
../include/TFEL/Material/Eurofer.hxx: In member function 'bool tfel::material::Eurofer<hypothesis, NumericType, false>::computeFdF(bool)':
../include/TFEL/Material/Eurofer.hxx:781:1: error: 'dfp_ddkhr_a0_0' was not declared in this scope; did you mean 'dfp1_ddkhr_a0_0'?
  781 | dfp_ddkhr_a0_0 += (2*(this->theta)*((this->khr_C0_0)/3))*(-dseq_ds/(this->young));
      | ^~~~~~~~~~~~~~
      | dfp1_ddkhr_a0_0
compilation terminated due to -Wfatal-errors.
The problem seems to come from the kinematic hardening because when I compile without this one, there is no more error and the library is built.

Can you help me, please ?
Best regards,
Guillaume

[behaviour.zip](https://github.com/thelfer/tfel/files/12701131/behaviour.zip)

**Comment by thelfer** [comment]
There a bug in the code generation. I'll fix that ASAP. Here is a quick and dirty workaround:

1. Generate the soure files:
    ```bash
    mfront --interface=generic behaviour.mfront
    ```
2. Edit the file `include/TFEL/Material/Test.hxx` and replace the line (798 in my version):
    ```c++
    dfp_ddkhr_a0_0 += (2*(this->theta)*((this->khr_C0_0)/3))*(-dseq_ds/(this->young));
    ```
    by
    ```c++
    dfp0_ddkhr_a0_0 += (2*(this->theta)*((this->khr_C0_0)/3))*(-dseq0_ds0/(this->young));
    ```
3. Compile the sources:
    ```bash
    mfront --obuild
    ```

**Comment by thelfer** [comment]
Note that another workaround is to use a numerical jacobian.

**Comment by gzumpichiat** [comment]
OK thanks you very much Thomas for this quick (and dirty :-) ) workaround ! It is working !

**Comment by thelfer** [comment]
@gzumpichiat Thanks for revealing this very old bug. You may want to upgrade your version to get the fix.
