### ISSUE TITLE
Allow result_type for @StaticVariable

### ISSUE THREAD

**Issue by dalphin5** [thelfer/tfel#484]
Dear Thomas,

It seems that the result_type<...> command does not work for @StaticVariable keyword. For example
@Parameter result<strain,time,OpDiv> this_is_ok=0.0;
is ok but 
@StaticVariable result<strain,time,OpDiv> not_ok=0.0;
does not compile.

However, surprisingly, predefined aliases seems to work, such as
@StaticVariable strainrate this_seems_to_work=0.0;

I also use this issue to mention that in the documentation of predefined aliases (https://thelfer.github.io/tfel/web/mfront-types.html), the type inv_length does not seem to work on a .mfront file.

**Comment by thelfer** [comment]
Let me check !

**Comment by thelfer** [comment]
To circumvent the issue, you may use:

```cxx
@StaticVariable strainrate not_ok=0.0;
```

**Comment by thelfer** [comment]
Fixed in `rliv-4.0`, `rliv-4.1`, `rliv-4.2`, and `master`.
Thanks @dalphin5 for reporting the issue !
