### ISSUE TITLE
CalculiX interface and change strain in 2.21 version 

### ISSUE THREAD

**Issue by 3rav** [thelfer/tfel#518]
Can the change in the deformation plasticity law in the new version 2.21 compared to the previous ones may affect the correctness of the results when using the Mfront library with CalculiX?

`Changed the deformation plasticity law from Cauchy stress vs. Euler strain to Cauchy stress vs. Hencky strain.`
http://www.dhondt.de/new_calc.htm

**Comment by thelfer** [comment]
Hi @3rav,
I don't think. I seems related to a specific law. To be sure, one needs to see if the interface for user defined behaviours changed.
