### ISSUE TITLE
[mtest] Creation of a wrapper around behaviours written in the logarithmic strain framework generated with the ASTER interface

### ISSUE THREAD

**Issue by arinamarchenko2021** [thelfer/tfel#55]
Hello Thomas,
Currently it is impossible to use MFRONT behavior written in logarithmic strain with MTEST via Aster interface. The only available solution is to compile MFRONT behavior with UMAT and run MTEST simulation with UMAT in large deformations.
It would be very useful to have this option available with ASTER interface, since we are running many identifications in large deformations (necessary for severe accidents, for example).

A very big thanks in advance.

Arina

**Comment by thelfer** [comment]
Fixed. Added 25 associated tests.
