### ISSUE TITLE
[mfront] Make the changes to issue #540 (fixed in #541) available in the last version 4.2.*.

### ISSUE THREAD

**Issue by OlivierFandeur** [thelfer/tfel#561]
As indicated in the title, we would like to have a **version rliv-4.2.*** of MFront that takes into account the changes made to ticket #540.

So that we can integrate this version into the future _version 2024 of Cast3M_, which is currently being finalised.

Yours faithfully

**Comment by thelfer** [comment]
@OlivierFandeur, no problem. This will be next week, to leave time to test the new version on Windows and Linux.
Is there a way to provide Cast3M's compilers for those plateforms ?

**Comment by thelfer** [comment]
https://github.com/thelfer/tfel/releases/tag/TFEL-4.2.1
