### ISSUE TITLE
MTestCurrentState.copy() produces a shallow copy in python bindings

### ISSUE THREAD

**Issue by LordKthulhu** [thelfer/tfel#567]
### Discussed in https://github.com/thelfer/tfel/discussions/564

<div type='discussions-op-text'>

<sup>Originally posted by **LordKthulhu** May 20, 2024</sup>
Hi Thomas,
I'm trying to get a deep copy of the `mtest` state in the `python` module. I create a state `s`, initialize it, copy it (`backup = s.copy()`), and run some calculations on the state `s`. I'm expecting the backup to hold the values of the initial states, but to the contrary it is as if the copy is shallow. I made a MWE: [MWE.zip](https://github.com/thelfer/tfel/files/15378770/MWE.zip). I was expecting `backup` to have the same value that I pulled from the state `s` as it was being copied.
Thanks in advance,

Maxime
</div>

**Comment by thelfer** [comment]
@LordKthulhu Could you give branch 567-mtestcurre... a try ? Seems working on your MWE.

**Comment by LordKthulhu** [comment]
Hi @thelfer,
Thank you so much for the quick fix ! I tested it and it seems the new method produces a proper deep copy of the state.

**Comment by thelfer** [comment]
Great. I'll merge it to master ASAP.
