### ISSUE TITLE
Extract the coordinates of the integration points for the PipeTest module in Python

### ISSUE THREAD

**Issue by akram-el-abdi** [thelfer/tfel#579]
Hi,

I need to access the coordinates of the integration points for the PipeTest module in Python.

Thank you in advance for your help.

Regards,

Akram

**Comment by thelfer** [comment]
Hi @akram-el-abdi, for which version do you need this (master, rliv-4.2, rliv-4.1, rliv-4.0) ?

**Comment by akram-el-abdi** [comment]
Hi Thomas,

The rliv-4.0

Thank you

**Comment by thelfer** [comment]
You now have access to the `position` member in the `CurrentState` object
