### ISSUE TITLE
[castem] Incorrect syntax in the dgibi example in case of 'ELASTIQUE' 'ORTHOTROPE' behavior

### ISSUE THREAD

**Issue by OlivierFandeur** [thelfer/tfel#639]
As described in the title. the `dgibi` example, created automatically by mfront in the directory `castem`, is not correct.

```
MO = 'MODELISER' v 'MECANIQUE' 'ELASTIQUE''ORTHOTROPE' 'NON_LINEAIRE'
'UTILISATEUR' 'LIB_LOI' 'libUmatX.so' 'FCT_LOI' 'umatX' 'C_MATERIAU' 
coel 'C_VARINTER' statev 'PARA_LOI' params 'CONS' M;
```

Its use leads to an error (not easily understandable).

When you read this `dgibi` file, after some time, you can see (it is not really obvious at the first time) that there is simply a space missing between the keywords `ELASTIQUE` and `ORTHOTROPE`.

NB1: In Fortran (so in `castem`), `'ELASTIQUE''ORTHOTROPE'` is read as the string `ELASTIQUE'ORTHOTROPE` and not as 2 character strings.

NB2: The same syntax error is expected in 'ELASTIQUE''ANISOTROPE' (not verified).

NB3: In general an isotropic behavior is used and the keyword 'ISOTROPIC' is not mandatory in this case (falsely?).

Thanks.

**Comment by thelfer** [comment]
This seems already corrected in all branches (I only checked a few). Here is the code generated by `OrthotropicElastic` example:

```
MO = 'MODELISER' v 'MECANIQUE' 'ELASTIQUE' 'ORTHOTROPE' 'NON_LINEAIRE'
'UTILISATEUR' 'LIB_LOI' 'libUmatBehaviour.so' 'FCT_LOI'
'umatorthotropicelastic' 'C_MATERIAU' coel 'PARA_LOI' params 'CONS' M;
```
