### ISSUE TITLE
Mfront first steps, issue with mtest

### ISSUE THREAD

**Issue by alexisbu** [thelfer/tfel#652]
Hello,

I am very sorry to start a discussion on such a basic issue. I searched for such error in the discussions but could not find it. 
I am trying to use mfront, and started with the simple norton test available in the tutorial folder (The ultimate goal is to use the work that T. Helfer has done with Joan Balaguer on the SOVS model).
Anyway, mfront is installed by my IT service on our linux nodes. 
They gave a csh script for it to work to set up the LD_LIBRAY_PATH in the correct folder.
The version used is 3.2.1. I tried the 4.2.1 but it gives an even worse error.

The mfront step is ok
>> mfront --obuild --interface=aster norton.mfront

Treating target : all
The following library has been built :
- libAsterBehaviour.so :  asternorton

But the mtest is not

>>mtest norton.mtest 

./src/libAsterBehaviour.so asternorton
No hypothesis defined, using default
terminate called after throwing an instance of 'std::runtime_error'
  what():  SingleStructureSchemeParser::SingleStructureScheme : error while parsing file 'norton.mtest' at line '1'.
ExternalLibraryManager::loadLibrary: library './src/libAsterBehaviour.so' could not be loaded, (./src/libAsterBehaviour.so: undefined symbol: _ZN5aster24AsterInterfaceExceptions36throwUnMatchedNumberOfStateVariablesERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEtl)

I can not figure out if it is because the installation was not done properly, if we have a missing library on our nodes, or if there is something wrong with the mtest script. Could you help ?
I have the same problem with interface castem. Also, le library libAsterBehaviour.so, or libUmatBehaviour.so is created as expected in the src folder.

Best regards,

Alexis B.

**Comment by thelfer** [comment]
Dear @alexisbu,

I expect that you have two conflicting versions of `mfront` installed.

Try running:

````
$ ldd ./src/libAsterBehaviour.so
````

and see if the linked librairies match the version of `MFront` that you used to compile the file.

Best,
Thomas

**Comment by alexisbu** [comment]
Thanks for your quick answer,

When I do that I get the following

    $ ldd ./src/libAsterBehaviour.so 
       
        linux-vdso.so.1 (0x00007ffcda1e6000)
        libAsterInterface.so => not found
        libMFrontProfiling.so => not found
        libTFELMaterial.so => not found
        libTFELMath.so => not found
        libTFELUtilities.so => not found
        libTFELException.so => not found
        libTFELNUMODIS.so => not found
        libTFELPhysicalConstants.so => not found
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00001525adb6f000)
        libm.so.6 => /lib64/libm.so.6 (0x00001525ad7ed000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00001525ad5d5000)
        libc.so.6 => /lib64/libc.so.6 (0x00001525ad1ff000)
        /lib64/ld-linux-x86-64.so.2 (0x00001525ae11c000)

Searching in the lib folder of the mfront installation, those marked "not found" are indeed missing. Funny because they appear in the folder of the version 4.2.1 that we also have. However, in this one, no interface (castem or aster) is present. I can only compile with the generic interface (and mtest still does not work, but this may come from me being unexperienced with the mtest scripts).
As I am also from CEA it would be ironic if mfront was not installed properly, but I want to be sure before asking to my IT.

Best regards,

Alexis B.

**Comment by thelfer** [comment]
> As I am also from CEA it would be ironic if mfront was not installed properly, but I want to be sure before asking to my IT.

I don't think it is ironic :)
We can use MFront in several solvers that only requires the `generic` interface, so generally, people install it only by selecting the interface that they are interested in.

So the real question is what solver do you want to use ? `Cast3M`, `code_aster` ?

**Comment by alexisbu** [comment]
I did not particularly want to use the old version, it just seemed to be the only one with at least two interface installed in the linux nodes we have.

I'd rather use cast3M for now because I never used code_aster.

So what would you recommend to make it work ? A new clean install with the desired interface ? or is there a way to install the castem interface as an add-on to the current 4.2.1 install ?

Best regards,

Considering the difficulties I might even consider install it on my windows laptop by myself.

**Comment by thelfer** [comment]
> So what would you recommend to make it work ? 

Would install Cast3M which ships with mfront ..

**Comment by alexisbu** [comment]
ok thanks for your help. I will come back once it works and that I have your sovs example working.

**Comment by alexisbu** [comment]
Hello,

I installed cast3M 2024 on my home profile on linux. 
Cast3M installation runs smoothly, then I added the following to my ~/.bashrc file

    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/ab263810/CASTEM2024/GCC/lib64/
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/ab263810/CASTEM2024/GCC/lib/
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/ab263810/CASTEM2024/MFRONT/lib/
    export PATH=/home/ab263810/CASTEM2024/MFRONT/bin:$PATH

mfront is then recognized, and if I run in the norton folder the mfront command, I got the following :

    Treating target : all
    umatNorton.cxx:10:9: fatal error: MFront/Castem/CastemOutOfBoundsPolicy.hxx: No such file or directory
     #include"MFront/Castem/CastemOutOfBoundsPolicy.hxx"
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    Norton.cxx:13:9: fatal error: TFEL/Raise.hxx: No such file or directory
     #include"TFEL/Raise.hxx"
             ^~~~~~~~~~~~~~~~
    compilation terminated.
    umatNorton.cxx:10:9: fatal error: MFront/Castem/CastemOutOfBoundsPolicy.hxx: No such file or directory
     #include"MFront/Castem/CastemOutOfBoundsPolicy.hxx"
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    make: *** [Makefile.mfront:37: umatNorton.o] Error 1
    callMake: can't build target 'all'
    libraries building went wrong
    Command was: make -C src -f Makefile.mfront all -s 

The local include folder contains only 
    $ ls include/*/*
    include/MFront/Castem:
    umatNorton.hxx
    
    include/TFEL/Material:
    NortonBehaviourData.hxx  Norton.hxx  NortonIntegrationData.hxx

I tried adding in the bashrc the following, without success.
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/ab263810/CASTEM2024/MFRONT/include/

So I desperately copy-pasted the whole include folder from the CASTEM24/MFRONT/ folder, in the local include/ which is created during compilation. I try re-running the compilation : 

      $ make -C src -f Makefile.mfront all -s
      /bin/ld: cannot find -lCastemInterface
      /bin/ld: cannot find -lMFrontProfiling
      /bin/ld: cannot find -lTFELMaterial
      /bin/ld: cannot find -lTFELMath
      /bin/ld: cannot find -lTFELUtilities
      /bin/ld: cannot find -lTFELException
      /bin/ld: cannot find -lTFELNUMODIS
      collect2: error: ld returned 1 exit status
      make: *** [Makefile.mfront:27: libUmatBehaviour.so] Error 1

Can you help ? I did not find this issue in the discussion.

Thanks for any help

Best regards.

**Comment by thelfer** [comment]
Normally you should source a file envCast3MWhatever to have everything set, including MFront.

If you only want MFront, just add TFELHOME as follows:

~~~~
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/ab263810/CASTEM2024/GCC/lib64/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/ab263810/CASTEM2024/GCC/lib/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/ab263810/CASTEM2024/MFRONT/lib/
export PATH=/home/ab263810/CASTEM2024/MFRONT/bin:$PATH
export TFELHOME=/home/ab263810/CASTEM2024/MFRONT
~~~

**Comment by alexisbu** [comment]
Hello,

Many thanks, your second solution worked perfectly, at least for the norton case. I will have a look on your first solution.

Thanks a lot for helping me getting started, I can now follow the tutorial.

Best regards,

Alexis

**Comment by thelfer** [comment]
If you send me an e-mail, I can send you many documentations that would ease the learning curve
