### ISSUE TITLE
[mfront] Single-crystal behaviours fails to compile with `intel/oneapi` (2021.1 and 2021.5) with `TFEL-3.4.3`

### ISSUE THREAD

**Issue by LionelGelebart** [thelfer/tfel#71]

**Comment by thelfer** [comment]
Le problème affecte les versions 3.4.x basés sur `C++-11`. Les versions 4.x  ne sont pas affectées
Les fonctions `offset*` ne devraient pas être déclarés `constexpr`.

**Comment by thelfer** [comment]
TFEL versions from 3.1 to 3.4 are affected.
