### ISSUE TITLE
Reference is not correctly rendered in the web

### ISSUE THREAD

**Issue by Irvise** [thelfer/tfel#73]
https://github.com/thelfer/tfel/blob/51bdadcc64bdfefb998754ac2ef9f59f29c27256/docs/web/behaviours.md?plain=1#L137

![image](https://user-images.githubusercontent.com/36135084/149023474-9210df8a-9379-4645-a40a-27384ca21705.png)

Edit: added another typo.

https://github.com/thelfer/tfel/blob/51bdadcc64bdfefb998754ac2ef9f59f29c27256/docs/web/behaviours.md?plain=1#L380

![image](https://user-images.githubusercontent.com/36135084/149024460-145ab5ad-ba50-42df-906f-b23e509e4795.png)

Edit 2:

This may be its own issue, but, in the Release section of Github, version 3.4.3 is marked as the latest/newest release, when (AFAIK) it should be 4.0.0. I personally do not know how to change it.

**Comment by thelfer** [comment]
> This may be its own issue, but, in the Release section of Github, version 3.4.3 is marked as the latest/newest release, when (AFAIK) it should be 4.0.0. I personally do not know how to change it.

I don't know either....
