### ISSUE TITLE
[TFELMaterial] The Mohr-Coulomb stress criterion is broken after PR #5

### ISSUE THREAD

**Issue by thelfer** [thelfer/tfel#81]
It seems like PR #5 broke the implementation of the Mohr-Coulomb stress criterion.

The attached implementations `MohrCoulomb2.mfront` and `MohrCoulomb3.mfront` do no compile with `TFEL-4.x` (it does with `TFEL-3.4.x`).

@nagelt, I know you're the culprit ! Would you please have a look ?

[MohrCoulomb.zip](https://github.com/thelfer/tfel/files/7870667/MohrCoulomb.zip)

**Comment by nagelt** [comment]
I'll take a look : )

**Comment by thelfer** [comment]
@Thanks @nagelt !

**Comment by thelfer** [comment]
Fixed by PR #103 in `master`.
